---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorino-serving-cert
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: authorino-serving-cert
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
