---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-enable-dsc-maas
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: enable-dsc-maas
    app.kubernetes.io/component: maas
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '13'
