---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enable-kuadrant-console-plugin
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: enable-kuadrant-console-plugin
    app.kubernetes.io/component: api-gateway-governance
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '14'
