---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-prepare-maas-gateway-tls
  labels:
    app.kubernetes.io/name: prepare-maas-gateway-tls
    app.kubernetes.io/component: maas-gateway
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '8'
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - get
  resourceNames:
  - default
