---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-prepare-maas-gateway-tls
  namespace: openshift-ingress
  labels:
    app.kubernetes.io/name: prepare-maas-gateway-tls
    app.kubernetes.io/component: maas-gateway
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '8'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-prepare-maas-gateway-tls
subjects:
- kind: ServiceAccount
  name: job-prepare-maas-gateway-tls
  namespace: openshift-ingress
