apiVersion: v1
kind: ServiceAccount
metadata:
  name: prepare-maas-route-access
  labels:
    app.kubernetes.io/name: prepare-maas-route-access
    app.kubernetes.io/component: maas
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '8'
  namespace: redhat-ods-applications
