---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-maas-db-credentials
  namespace: models-as-a-service-db
  labels:
    app.kubernetes.io/name: wait-maas-db-credentials
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '6'
