apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kueue-operator
  namespace: openshift-kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/name: kueue-operator
    app.kubernetes.io/part-of: gpu-infra
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: argocd
spec:
  channel: stable-v1.4
  installPlanApproval: Automatic
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
