apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: rhoai-demo-pv-pool
  namespace: openshift-storage
  labels:
    app.kubernetes.io/name: rhoai-local-object-storage
    app.kubernetes.io/part-of: rhoai-platform
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=false
spec:
  type: pv-pool
  pvPool:
    numVolumes: 1
    storageClass: gp3-csi
    resources:
      requests:
        storage: 100Gi
