#!/usr/bin/env python3
"""compat-mapping build_plugins[openapi-generator].generators[jaxrs-spec].required_read_only,
generated and validated offline on the pinned platform's Bean Validation.

A request-body schema with a `required` + readOnly array (the shape of the
v28 Owner.pets) and a required string is generated by openapi-generator
jaxrs-spec/quarkus 7.25.0 with the destination's options, twice:

  default   7.25.0's own templates: the readOnly required array gets no
            @NotNull, so an explicit null validates clean (the M-3 v28 500)
  override  the catalog's action: <templateDirectory> holding 7.25.0's own
            JavaJaxRS/spec/beanValidation.mustache with only the {{^isReadOnly}}
            guard removed

and a probe deserializes three bodies with Jackson and validates them with
Hibernate Validator (the pinned BOM's): the override refuses the explicit
null with the platform's default 'must not be null' and still accepts the
omitted property (the initialized empty collection, V16-8) and an empty one;
the required string keeps its @NotNull in both. The template text is read
from the plugin's own jar, never retyped. SKIP with the reason when mvn,
java or the artifacts are not available offline.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import test_runtime_fixture as rt  # noqa: E402

GOLDEN = rt.GOLDEN
GENERATOR = Path.home() / ".m2" / "repository" / "org" / "openapitools" / "openapi-generator" / "7.25.0" / "openapi-generator-7.25.0.jar"
TEMPLATE = "JavaJaxRS/spec/beanValidation.mustache"
GUARD_OPEN, GUARD_CLOSE = "{{^isReadOnly}}", "{{/isReadOnly}}"

SPEC = """openapi: 3.0.1
info: {title: probe, version: '1'}
paths: {}
components:
  schemas:
    Crate:
      type: object
      properties:
        name: {type: string, maxLength: 30}
        labels:
          type: array
          items: {type: string}
          readOnly: true
      required: [name, labels]
"""

POM = """<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId><artifactId>required-readonly</artifactId><version>1.0</version>
  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencyManagement><dependencies><dependency>
    <groupId>${quarkus.platform.group-id}</groupId><artifactId>quarkus-bom</artifactId>
    <version>${quarkus.platform.version}</version><type>pom</type><scope>import</scope>
  </dependency></dependencies></dependencyManagement>
  <dependencies>
    <dependency><groupId>org.hibernate.validator</groupId><artifactId>hibernate-validator</artifactId></dependency>
    <dependency><groupId>org.glassfish.expressly</groupId><artifactId>expressly</artifactId></dependency>
    <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId></dependency>
    <dependency><groupId>jakarta.annotation</groupId><artifactId>jakarta.annotation-api</artifactId></dependency>
  </dependencies>
  <build><plugins><plugin>
    <groupId>org.openapitools</groupId><artifactId>openapi-generator-maven-plugin</artifactId><version>7.25.0</version>
    <executions><execution><goals><goal>generate</goal></goals><configuration>
      <inputSpec>${project.basedir}/spec.yml</inputSpec>
      <generatorName>jaxrs-spec</generatorName><library>quarkus</library>
      <modelPackage>org.acme.dto</modelPackage><modelNameSuffix>Dto</modelNameSuffix>
      <generateApis>false</generateApis><generateSupportingFiles>false</generateSupportingFiles>
      <generateModelTests>false</generateModelTests><generateModelDocumentation>false</generateModelDocumentation>
      %s
      <configOptions>
        <useJakartaEe>true</useJakartaEe><useBeanValidation>true</useBeanValidation><openApiNullable>false</openApiNullable>
        <useMicroProfileOpenAPIAnnotations>false</useMicroProfileOpenAPIAnnotations><sourceFolder>src/main/java</sourceFolder>
        <generateJsonCreator>false</generateJsonCreator><dateLibrary>java8</dateLibrary>
      </configOptions>
    </configuration></execution></executions>
  </plugin></plugins></build>
</project>
"""

PROBE = """package org.acme;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.*;
import java.util.*;
import org.acme.dto.CrateDto;
public class Probe {
  public static void main(String[] a) throws Exception {
    ObjectMapper om = new ObjectMapper();
    Validator v = Validation.buildDefaultValidatorFactory().getValidator();
    String[] bodies = {"{\\"name\\":\\"n\\"}", "{\\"name\\":\\"n\\",\\"labels\\":null}", "{\\"name\\":\\"n\\",\\"labels\\":[]}", "{\\"labels\\":[]}"};
    String[] names = {"omitted", "null", "empty", "no-name"};
    for (int i = 0; i < bodies.length; i++) {
      List<String> out = new ArrayList<>();
      for (ConstraintViolation<CrateDto> cv : v.validate(om.readValue(bodies[i], CrateDto.class))) out.add(cv.getPropertyPath() + ":" + cv.getMessage());
      Collections.sort(out);
      System.out.println(names[i] + "=" + String.join(",", out));
    }
  }
}
"""


def _mvn(root: Path, *goals: str) -> subprocess.CompletedProcess:
    pin = rt.pin()
    return subprocess.run(["mvn", "-B", "-q", "-o", "-s", str(GOLDEN / ".mvn" / "settings.xml"),
                           "-Dquarkus.platform.group-id=%s" % pin["group_id"], "-Dquarkus.platform.version=%s" % pin["version"],
                           *goals], cwd=str(root), text=True, capture_output=True, timeout=900)


def variant(td: Path, name: str, override: str | None) -> dict:
    root = td / name
    (root / "src/main/java/org/acme").mkdir(parents=True)
    (root / "spec.yml").write_text(SPEC, encoding="utf-8")
    tpl = ""
    if override is not None:
        (root / "src/main/openapi-templates").mkdir(parents=True)
        (root / "src/main/openapi-templates/beanValidation.mustache").write_text(override, encoding="utf-8")
        tpl = "<templateDirectory>${project.basedir}/src/main/openapi-templates</templateDirectory>"
    (root / "pom.xml").write_text(POM % tpl, encoding="utf-8")
    (root / "src/main/java/org/acme/Probe.java").write_text(PROBE, encoding="utf-8")
    p = _mvn(root, "package", "dependency:build-classpath", "-Dmdep.outputFile=cp.txt")
    if p.returncode != 0:
        out = p.stdout + p.stderr
        hit = next((n for n in rt._OFFLINE if n in out), "")
        if hit:
            raise rt.Skip("the artifacts are not all in the local Maven repository (%s)" % hit)
        raise RuntimeError("%s does not build: %s" % (name, out[-900:]))
    dto = next(root.rglob("CrateDto.java")).read_text(encoding="utf-8")
    cp = "%s:%s" % (root / "target" / "classes", (root / "cp.txt").read_text().strip())
    r = subprocess.run(["java", "-cp", cp, "org.acme.Probe"], capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        raise RuntimeError("%s probe failed: %s" % (name, (r.stderr or r.stdout)[-600:]))
    rows = dict(ln.split("=", 1) for ln in r.stdout.strip().splitlines())
    getter = next((ln for ln in dto.splitlines() if "getLabels()" in ln), "")
    return {"getter": getter.strip(), "rows": rows}


def main() -> int:
    try:
        rt.need_tools("mvn", "java", "javac")
        if not GENERATOR.is_file():
            raise rt.Skip("openapi-generator 7.25.0 is not in the local Maven repository")
        with zipfile.ZipFile(GENERATOR) as z:
            original = z.read(TEMPLATE).decode("utf-8")
        if original.count(GUARD_OPEN) != 1 or original.count(GUARD_CLOSE) != 1:
            print("FAIL: 7.25.0's %s no longer has exactly one readOnly guard; the catalog row is stale" % TEMPLATE, file=sys.stderr)
            return 1
        override = original.replace(GUARD_OPEN, "").replace(GUARD_CLOSE, "")
        with tempfile.TemporaryDirectory(prefix="required-readonly-") as tds:
            td = Path(tds)
            got = {"default": variant(td, "default", None), "override": variant(td, "override", override)}
    except rt.Skip as exc:
        print("SKIP: generated-required-readonly: %s" % exc)
        return 0
    except RuntimeError as exc:
        print("FAIL: generated-required-readonly: %s" % exc, file=sys.stderr)
        return 1
    for k, v in got.items():
        print("%-9s getter: %s | %s" % (k, v["getter"], v["rows"]))
    d, o = got["default"], got["override"]
    if "@NotNull" in d["getter"] or d["rows"].get("null") != "":
        print("FAIL: the default 7.25.0 model omits @NotNull on the readOnly required array and validates an explicit null clean",
              file=sys.stderr)
        return 1
    if "@NotNull" not in o["getter"] or o["rows"].get("null") != "labels:must not be null":
        print("FAIL: the override refuses the explicit null with 'must not be null'", file=sys.stderr)
        return 1
    if o["rows"].get("omitted") != "" or o["rows"].get("empty") != "":
        print("FAIL: the override still accepts an omitted (initialized) and an empty collection (V16-8)", file=sys.stderr)
        return 1
    if d["rows"].get("no-name") != "name:must not be null" or o["rows"].get("no-name") != "name:must not be null":
        print("FAIL: a required non-readOnly property keeps @NotNull in both", file=sys.stderr)
        return 1
    print("OK: generated-required-readonly (openapi-generator jaxrs-spec/quarkus 7.25.0 offline, pinned platform %s Bean "
          "Validation: the default template omits @NotNull on a required readOnly array and an explicit null validates clean; "
          "the catalog's template override refuses it with 'must not be null' and still accepts omitted and empty)"
          % rt.pin()["version"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
