#!/usr/bin/env python3
"""V17-4 runtime proof: request-body cases over HTTP against the generator
configuration the plan selects, on a booted Quarkus app.

fixtures/handler-validation-package's request body OwnerDto is GENERATED by
openapi-generator 7.25.0 (jaxrs-spec, library quarkus, useBeanValidation=true)
from a spec whose Owner lists firstName, lastName and pets (a collection) as
required; the handler validates the body itself (the BindingResult
translation). It is packaged twice: with the V17-4 recipe's action
(generateJsonCreator=false) and with the generator's default (true).

For the required COLLECTION (pets) and a required SCALAR (lastName), each of
omitted / explicit null / empty / invalid-constraint / invalid-type is its own
request, and the status of each is recorded under both configurations.

Asserted -- only what the source's captures and the recipe state:
  * omitted collection: 201 with generateJsonCreator=false (the source's
    capture: a create without `pets` answered 201) and 400 with the default
    (the v17 defect: the @JsonCreator refuses it before the handler);
  * invalid values (constraint violation, wrong JSON type): 400 under both.
Every other cell is reported as "observed, no source capture": no source
expectation is invented for it.

A missing prerequisite prints SKIP with the reason and exits 0.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _runtime_fixture as rt  # noqa: E402

FIXTURE = rt.FIXTURES / "handler-validation-package"
BASE = {"firstName": "Ada", "lastName": "Byron", "pets": [{"name": "Rex"}]}


def _body(prop: str, case: str):
    b = {k: (list(v) if isinstance(v, list) else v) for k, v in BASE.items()}
    if case == "omitted":
        b.pop(prop)
    elif case == "null":
        b[prop] = None
    elif case == "empty":
        b[prop] = [] if prop == "pets" else ""
    elif case == "invalid-constraint":
        b[prop] = [{"name": ""}] if prop == "pets" else "x" * 31
    elif case == "invalid-type":
        b[prop] = "not-a-list" if prop == "pets" else {"a": 1}
    return b


CASES = [(p, c) for p in ("pets", "lastName") for c in ("omitted", "null", "empty", "invalid-constraint", "invalid-type")]
# (property, case) -> expected status per configuration, only where the source or the recipe says so
ASSERTED = {("pets", "omitted"): {"false": 201, "true": 400},
            ("pets", "invalid-constraint"): {"false": 400, "true": 400},
            ("pets", "invalid-type"): {"false": 400, "true": 400},
            ("lastName", "invalid-constraint"): {"false": 400, "true": 400},
            ("lastName", "invalid-type"): {"false": 400, "true": 400}}


def main() -> int:
    table: dict[tuple[str, str], dict[str, int]] = {}
    try:
        rt.need_tools("mvn", "java", "javac")
        with tempfile.TemporaryDirectory(prefix="request-body-rt-") as td:
            for creator in ("false", "true"):
                root = Path(td) / ("json-creator-%s" % creator)
                shutil.copytree(FIXTURE, root)
                ok, out = rt.package(root, "-Dfixture.generateJsonCreator=%s" % creator)
                if not ok:
                    print("FAIL: generateJsonCreator=%s packages: %s" % (creator, out[-900:]), file=sys.stderr)
                    return 1
                with rt.boot(root, "/ledger/api/owners") as base:
                    url = base + "/ledger/api/owners"
                    st, _h, _b = rt.http("POST", url, BASE)
                    if st != 201:
                        print("FAIL: the complete valid body must answer 201 under generateJsonCreator=%s: %s" % (creator, st),
                              file=sys.stderr)
                        return 1
                    for prop, case in CASES:
                        table.setdefault((prop, case), {})[creator] = rt.http("POST", url, _body(prop, case))[0]
    except rt.Skip as exc:
        print("SKIP: request-body-runtime: %s" % exc)
        return 0
    bad = []
    print("%-9s %-19s %-22s %-22s %s" % ("property", "case", "generateJsonCreator=false", "=true (default)", "expectation"))
    for key in CASES:
        got = table[key]
        want = ASSERTED.get(key)
        note = "asserted %s" % want if want else "observed, no source capture"
        if want and any(got[c] != want[c] for c in want):
            bad.append("%s %s: %s, expected %s" % (key[0], key[1], got, want))
        print("%-9s %-19s %-22s %-22s %s" % (key[0], key[1], got["false"], got["true"], note))
    if bad:
        print("FAIL: %s" % "; ".join(bad), file=sys.stderr)
        return 1
    print("OK: request-body-runtime (pinned platform %s, openapi-generator 7.25.0 jaxrs-spec/quarkus, packaged jar over HTTP, "
          "10 distinct omitted/null/empty/invalid requests per configuration: the omitted required collection answers 201 "
          "with generateJsonCreator=false and 400 with the default; constraint and type violations answer 400 under both; "
          "the remaining cells are reported as observed, with no source capture)" % rt.pin()["version"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
