apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/name: nfd-instance
    app.kubernetes.io/part-of: gpu-infra
    app.kubernetes.io/component: hardware-discovery
    app.kubernetes.io/managed-by: argocd
spec:
  operand:
    imagePullPolicy: IfNotPresent
    servicePort: 12000
    image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9@sha256:7753deaab79b1cf01b73eb19c32a622283a37348acdef14a29978947ff91a8e7
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist: ["0200", "03", "12"]
          deviceLabelFields: [vendor]
