apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: authorino
    app.kubernetes.io/component: authorization
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterWide: true
  replicas: 1
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-server-cert
  oidcServer:
    tls:
      enabled: false
  volumes:
    items:
      - name: openshift-service-ca
        mountPath: /etc/pki/tls/certs
        configMaps:
          - authorino-service-ca
        items:
          - key: service-ca.crt
            path: openshift-service-ca.crt
