apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kuadrant.yaml
  - ipp-response-passthrough-envoyfilter.yaml
  - authorino-service.yaml
  - authorino.yaml
