apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-enable-dsc-kueue
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: enable-dsc-kueue
    app.kubernetes.io/component: platform-configuration
    app.kubernetes.io/part-of: gpu-infra
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
