apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: qwen3-6-35b-a3b
  namespace: maas
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  modelRef:
    kind: LLMInferenceService
    name: qwen3-6-35b-a3b
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: nemotron-3-nano-30b-a3b
  namespace: maas
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  modelRef:
    kind: LLMInferenceService
    name: nemotron-3-nano-30b-a3b
