apiVersion: v1
kind: Namespace
metadata:
  name: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-wave: "16"
  labels:
    app.kubernetes.io/name: models-as-a-service
    app.kubernetes.io/part-of: models-as-a-service
