apiVersion: v1
kind: ServiceAccount
metadata:
  name: enable-pipelines-console-plugin
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enable-pipelines-console-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "10"
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enable-pipelines-console-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "10"
subjects:
  - kind: ServiceAccount
    name: enable-pipelines-console-plugin
    namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enable-pipelines-console-plugin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enable-pipelines-console-plugin
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  enable-console-plugin.sh: |
    #!/bin/bash
    set -euo pipefail

    function noisy {
        set -x
        "${@}"
        { set +x; } 2>/dev/null
    }
    PLUGIN_NAME="${PLUGIN_NAME:-pipelines-console-plugin}"

    echo "Ensuring ${PLUGIN_NAME} plugin is enabled"
    echo ""

    if [ -z "$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}' 2>/dev/null)" ]; then
        echo "Creating plugins object"
        noisy oc patch consoles.operator.openshift.io cluster --patch '{ "spec": { "plugins": [] } }' --type=merge
    fi

    installed_plugins=$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')
    echo "Current plugins:"
    echo "${installed_plugins}"

    if [[ "${installed_plugins}" == *"${PLUGIN_NAME}"* ]]; then
        echo "${PLUGIN_NAME} is already enabled"
    else
        echo "Enabling plugin: ${PLUGIN_NAME}"
        noisy oc patch consoles.operator.openshift.io cluster --type=json --patch '[{"op": "add", "path": "/spec/plugins/-", "value": "'"${PLUGIN_NAME}"'"}]'
    fi

    sleep 6
    noisy oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: enable-pipelines-console-plugin
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: enable-pipelines-console-plugin
      containers:
        - name: enable-plugin
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/tools:latest'
          env:
            - name: PLUGIN_NAME
              value: pipelines-console-plugin
          command: ["/bin/bash"]
          args:
            - /app/enable-console-plugin.sh
          volumeMounts:
            - name: enable-plugin
              mountPath: /app
      volumes:
        - name: enable-plugin
          configMap:
            name: enable-pipelines-console-plugin
            defaultMode: 0755
