#!/usr/bin/env python3
"""V16-8 package-level fixture: the BindingResult translation and the
generated-body option, packaged and run on the pinned Spring compatibility
stack -- executable valid/invalid request regressions, not word checks.

fixtures/handler-validation-package is a Spring Web controller (quarkus-spring-web,
quarkus-rest-jackson, quarkus-hibernate-validator, the pinned platform BOM)
whose request body OwnerDto is GENERATED by openapi-generator 7.25.0
(jaxrs-spec, library quarkus, useBeanValidation=true) from a spec that lists
`pets` as required. The handlers validate the body themselves, as the
BindingResult translation says: `bindingResult.hasErrors() || dto.getId() !=
null` became `!violations.isEmpty() || ownerDto.getId() != null`, and no
@Valid on the parameter. Persistence is an in-memory store the GET lists.

Asked of the real platform, offline, from the local Maven repository:

  * the faithful fixture (generateJsonCreator=false): a valid create WITHOUT
    `pets` (the source's accepted-body contract) answers 201 with its Location
    under /ledger, a valid update 204; a blank field, a nested invalid pet and a
    create that sends an id are refused 400 with the source-shaped `errors`
    header naming what was wrong; and only the valid create is persisted;
  * each defect is caught by the same requests: the INVERTED guard
    (`violations.isEmpty() || ...`, v16's 13 sites) refuses the valid create;
    `&&` for `||` persists an invalid create (201 for a blank field); a KEPT @Valid answers an
    invalid body with the platform's own report and no `errors` header; and
    the generator's default generateJsonCreator=true refuses the valid body
    that omits the required collection.

What this does NOT run: a database (the store is in memory) and the Spring
source itself (the source-shaped responses are the fixture's contract).

When the local environment cannot package or start it (no mvn, java or javac;
the pinned or generator artifacts not in the local Maven repository; no
loopback port), the case prints SKIP with the precise reason and exits 0.
"""
from __future__ import annotations

import json
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
GOLDEN = HERE.parents[4]
FIXTURE = HERE.parent / "fixtures" / "handler-validation-package"
CONTROLLER = "src/main/java/org/acme/ledger/rest/OwnerRestController.java"
_OFFLINE = ("Cannot access", "offline mode", "Could not resolve", "could not be resolved",
            "Non-resolvable import POM", "has not been downloaded")
GUARD = "if (!violations.isEmpty() || ownerDto.getId() != null) {"
PARAM = "public ResponseEntity<OwnerDto> addOwner(@RequestBody OwnerDto ownerDto,"
# each defect, as the text it replaces in the faithful fixture
DEFECTS = {
    "inverted-guard": (GUARD, "if (violations.isEmpty() || ownerDto.getId() != null) {"),
    "and-for-or": (GUARD, "if (!violations.isEmpty() && ownerDto.getId() != null) {"),
    "valid-kept": (PARAM, "public ResponseEntity<OwnerDto> addOwner(@RequestBody @jakarta.validation.Valid OwnerDto ownerDto,"),
}


class Skip(Exception):
    pass


def _fail(msg: str) -> int:
    print("FAIL: " + msg, file=sys.stderr)
    return 1


def _pin() -> dict:
    return json.loads((GOLDEN / ".hermes" / "pins.json").read_text(encoding="utf-8"))["pins"]["quarkus_platform"]


def _package(root: Path, json_creator: str) -> tuple[bool, str]:
    pin = _pin()
    p = subprocess.run(["mvn", "-B", "-q", "-o", "-s", str(GOLDEN / ".mvn" / "settings.xml"),
                        "-Dquarkus.platform.group-id=%s" % pin["group_id"],
                        "-Dquarkus.platform.version=%s" % pin["version"],
                        "-Dfixture.generateJsonCreator=%s" % json_creator, "package", "-DskipTests"],
                       cwd=str(root), text=True, capture_output=True, timeout=900)
    out = p.stdout + p.stderr
    if p.returncode != 0:
        hit = next((n for n in _OFFLINE if n in out), "")
        if hit:
            raise Skip("the pinned platform's or the generator's artifacts are not all in the local Maven repository (%s)"
                       % next((ln.strip() for ln in out.splitlines() if hit in ln), hit)[:240])
    return p.returncode == 0, out


def _http(method: str, url: str, body: dict | None = None) -> tuple[int, dict, str]:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method,
                                 headers={"Content-Type": "application/json"} if data is not None else {})
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:  # noqa: S310 - the fixture's own loopback app
            return int(resp.status), {k.lower(): v for k, v in resp.headers.items()}, resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        return int(exc.code), {k.lower(): v for k, v in exc.headers.items()}, exc.read().decode("utf-8", "replace")


def _exercise(root: Path) -> dict:
    """Start the packaged app and send the source's requests; what came back."""
    try:
        with socket.socket() as s:
            s.bind(("127.0.0.1", 0))
            port = s.getsockname()[1]
    except OSError as exc:
        raise Skip("no loopback port to start the packaged application on (%s)" % exc)
    log = (root / "run.log").open("w")
    proc = subprocess.Popen(["java", "-Dquarkus.http.host=127.0.0.1", "-Dquarkus.http.port=%d" % port,
                             "-jar", str(root / "target" / "quarkus-app" / "quarkus-run.jar")],
                            cwd=str(root), stdout=log, stderr=subprocess.STDOUT)
    base = "http://127.0.0.1:%d/ledger/api/owners" % port
    try:
        deadline = time.time() + 60
        while True:
            try:
                _http("GET", base)
                break
            except (urllib.error.URLError, ConnectionError, OSError):
                if proc.poll() is not None or time.time() > deadline:
                    raise RuntimeError("the packaged application did not start: %s" % (root / "run.log").read_text()[-600:])
                time.sleep(0.5)
        got = {"base": base}
        # the source's valid create body omits the spec-required collection
        got["create"] = _http("POST", base, {"firstName": "Ada", "lastName": "Byron"})
        got["update"] = _http("PUT", base + "/1", {"firstName": "Ada", "lastName": "Lovelace"})
        got["blank"] = _http("POST", base, {"firstName": "", "lastName": "Byron"})
        got["nested"] = _http("POST", base, {"firstName": "Ada", "lastName": "Byron", "pets": [{"name": ""}]})
        got["with_id"] = _http("POST", base, {"id": 99, "firstName": "Ada", "lastName": "Byron"})
        got["list"] = _http("GET", base)
        return got
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=20)
        except subprocess.TimeoutExpired:
            proc.kill()
        log.close()


def _faithful(got: dict) -> str:
    """'' when every response is the source's, else what differs."""
    base = got["base"]
    st, h, body = got["create"]
    if st != 201 or h.get("location") != base + "/1" or json.loads(body or "{}").get("id") != 1:
        return "a valid create without the required collection answers 201 with Location %s/1: %s %s %s" % (base, st, h.get("location"), body[:120])
    if got["update"][0] != 204:
        return "a valid update answers 204: %s" % (got["update"][:1],)
    for key, field in (("blank", "firstName"), ("nested", "pets[0].name"), ("with_id", "id")):
        st, h, _b = got[key]
        if st != 400 or field not in str(h.get("errors") or ""):
            return "%s is refused 400 with the source's errors header naming %s: %s errors=%r" % (key, field, st, h.get("errors"))
    listed = json.loads(got["list"][2] or "[]")
    if [o.get("id") for o in listed] != [1] or listed[0].get("lastName") != "Lovelace":
        return "only the valid create is persisted (and updated): %s" % listed
    return ""


def main() -> int:
    for tool in ("mvn", "java", "javac"):
        if not shutil.which(tool):
            print("SKIP: handler-validation-package: %s is not on PATH, so the platform cannot package and run the fixture here" % tool)
            return 0
    rows: list[str] = []
    try:
        with tempfile.TemporaryDirectory(prefix="handler-validation-pkg-") as td:
            pristine = FIXTURE / CONTROLLER

            def build(label: str, edit: tuple[str, str] | None, json_creator: str) -> tuple[bool, str, dict | None]:
                root = Path(td) / label
                shutil.copytree(FIXTURE, root)
                if edit:
                    text = pristine.read_text(encoding="utf-8")
                    if edit[0] not in text:
                        raise RuntimeError("the fixture no longer carries %r" % edit[0])
                    (root / CONTROLLER).write_text(text.replace(edit[0], edit[1], 1), encoding="utf-8")
                ok, out = _package(root, json_creator)
                return ok, out, (_exercise(root) if ok else None)

            ok, out, got = build("faithful", None, "false")
            if not ok:
                return _fail("the faithful fixture packages: %s" % out[-900:])
            why = _faithful(got)
            if why:
                return _fail("faithful translation: %s" % why)
            rows.append("faithful: 201+Location, 204, three 400s with errors, one persisted")
            for label, edit in DEFECTS.items():
                ok, out, got = build(label, edit, "false")
                if not ok:
                    return _fail("%s still packages (the defect is behavioural): %s" % (label, out[-600:]))
                why = _faithful(got)
                if not why:
                    return _fail("%s must be caught by the requests, and every one answered as the source" % label)
                # the request each defect breaks, and how
                st, h, _b = got["create"] if label == "inverted-guard" else got["blank"]
                caught = {"inverted-guard": st == 400,                                   # the valid create refused
                          "and-for-or": st == 201,                                        # an invalid create persisted
                          "valid-kept": st == 400 and not h.get("errors")}[label]         # the platform's own report
                if not caught:
                    return _fail("%s is caught by the request it breaks: %s %s %s" % (label, st, h.get("errors"), why))
                rows.append({"inverted-guard": "inverted guard: the valid create answers %s",
                             "and-for-or": "&& for ||: the blank-field create answers %s and is persisted",
                             "valid-kept": "@Valid kept: the blank-field create answers %s with no errors header"}[label] % st)
            ok, out, got = build("json-creator-default", None, "true")
            if not ok:
                return _fail("the generator default still packages: %s" % out[-600:])
            st = got["create"][0]
            if st != 400:
                return _fail("with generateJsonCreator=true the body without the required collection is refused 400 at the "
                             "boundary: %s" % st)
            rows.append("generateJsonCreator=true: the valid create without pets answers %d" % st)
    except Skip as exc:
        print("SKIP: handler-validation-package: %s" % exc)
        return 0
    except RuntimeError as exc:
        return _fail(str(exc))
    print("OK: handler-validation-package (pinned platform %s, openapi-generator jaxrs-spec 7.25.0, offline; %s)"
          % (_pin()["version"], "; ".join(rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
