apiVersion: v1
kind: Service
metadata:
  name: evalhub-postgresql
  namespace: evalhub
  labels:
    app.kubernetes.io/part-of: rhoai-platform
    app.kubernetes.io/name: evalhub-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  selector:
    app.kubernetes.io/name: evalhub-postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
