apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  labels:
    app.kubernetes.io/managed-by: maas-observability
    app.kubernetes.io/part-of: maas-observability
  name: latency-per-subscription
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  metrics:
  - overrides:
    - match:
        metric: REQUEST_DURATION
        mode: CLIENT_AND_SERVER
      tagOverrides:
        subscription:
          operation: UPSERT
          value: request.headers["x-maas-subscription"]
    providers:
    - name: prometheus
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: maas-default-gateway
