apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cq-cpu-default.yaml
  - cq-gpu-shared.yaml
  - cq-gpu-priority.yaml
  - cq-gpu-reserved-demo.yaml
  - default-flavor.yaml
  - gpu-l40s.yaml
  - lq-cpu-default.yaml
  - lq-gpu-shared.yaml
  - lq-gpu-priority.yaml
  - lq-gpu-reserved-demo.yaml
  - gpu-high-priority.yaml
