apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# LLM Serving with Models-as-a-Service
# Ref: https://docs.redhat.com/en/learn/ai-quickstarts/rh-maas-code-assistant

resources:
  - models/namespace.yaml
  - models/gpt-oss-20b.yaml
  - models/nemotron-3-nano-30b.yaml
  - governance/maas-groups.yaml
  - governance/ratelimitpolicy.yaml
  - governance/tokenratelimitpolicy.yaml
  - governance/telemetrypolicy.yaml
