#!/usr/bin/env bash
# O-DEFAULTAUDIT — emit fail-open / fail-closed defaults inventory.
# O-DEFAULTRG — harvest via grep -nE (PATH-tolerant); never rg (absent on
# many hosts/pods → silent empty fences + false GREEN --check).
#
# Greps plan-lint.py + supervisor.sh for guard-input defaults and classifies
# each as permissive (fail-open) or restrictive (fail-closed). Writes
# `.hermes/harness/defaults-inventory.md` (artefact) and prints a summary.
#
# Usage:
#   bash .hermes/harness/defaults-inventory.sh
#   bash .hermes/harness/defaults-inventory.sh --check   # fail if artefact stale
set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${HARNESS_DIR}/defaults-inventory.md"
LINT="${HARNESS_DIR}/plan-lint.py"
SUP="${HARNESS_DIR}/supervisor.sh"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# O-DEFAULTRG: grep -nE only (no rg). Empty harvest is RED, not silent GREEN.
_grepn() {
  # $1=ERE pattern  $2=file — stdout lines; never fail the pipe on "no match"
  grep -nE "$1" "$2" 2>/dev/null || true
}

# Assert both harvest fences contain ≥1 numbered hit (NNN:…).
# Extract lines BETWEEN opening/closing ``` after each ### section
# (sed '/###/,/^```$/' stops at the opening fence — wrong).
assert_fence_harvest() {
  local f="$1"
  local pl_n sup_n
  pl_n=$(awk '
    /^### plan-lint\.py/ { sec=1; next }
    sec && /^```$/ { if (in_fence) { exit } in_fence=1; next }
    sec && in_fence { print }
  ' "$f" | grep -cE '^[0-9]+:' || true)
  sup_n=$(awk '
    /^### supervisor\.sh/ { sec=1; next }
    sec && /^```$/ { if (in_fence) { exit } in_fence=1; next }
    sec && in_fence { print }
  ' "$f" | grep -cE '^[0-9]+:' || true)
  if [ "${pl_n:-0}" -lt 1 ] || [ "${sup_n:-0}" -lt 1 ]; then
    echo "O-DEFAULTRG: empty fence harvest (plan-lint=${pl_n:-0} supervisor=${sup_n:-0}) — refuse GREEN" >&2
    return 1
  fi
  return 0
}

tmp="$(mktemp)"
{
  cat <<'EOF'
# Harness defaults inventory (O-DEFAULTAUDIT)

**Purpose:** enumerate guard-input defaults and classify each as
**permissive** (fail-open — missing/undeclared → proceed) or
**restrictive** (fail-closed — missing/undeclared → RED/skip/HOLD).

Generated by `defaults-inventory.sh`. Re-run after changing
`plan-lint.py` / `supervisor.sh` defaults. Seeded from Wave4 §2.3 known
cases; the script appends grep-discovered `${VAR:-default}` / env-get
patterns for review.

| ID / site | Default | Class | Notes |
|-----------|---------|-------|-------|
| O-INFERABSENT (plan-lint) | LINT tier (fails PLAN OK) | restrictive | Wave4 §2.2 — WARN→LINT landed; proceed via Shape=create\|verify or `Proceed: O-NULLACTION` |
| Oracle field (supervisor `task_oracle`) | **derived** present\|absent from filesystem | restrictive | O-ORACLEDERIVE §2.1 — never `else present`; legacy test OR dest Target |
| `Proceed: O-NULLACTION` (O-INFERABSENT) | unset → block | restrictive (override opt-in) | One-line non-punitive proceed for fixtures / honest stop — not a silent default |
| `PLAN_LINT_REQUIRE_SHAPE` (plan-lint) | HARD / require Shape (`True`) when unset | restrictive | O-M3SHAPEHARD; softened only by `PLAN_LINT_REQUIRE_SHAPE=0` or `PLAN_LINT_SHAPE_WARN=1` |
| `PLAN_LINT_SHAPE_WARN` (instruments suite) | suite exports `1` (WARN grandfather) | permissive (fixture-only) | Live M3 / outer-loop unset — hard bar |
| `STORY_DEPLOY` (supervisor) | `true` when unset | restrictive for deploy stories | Non-deploy stories must pass `false` explicitly (O-M3ACCEPT / O-SUPACCEPT) |
| `--story-deploy` (plan-lint CLI) | `True` when flag omitted | restrictive vs non-deploy | Instruments that omit flag behave as deploy=true |
| Retest-owed bank rows | ✅ allowed with prose debt | permissive | Wave4 §1.3 — ✅-without-corpus-discharge; close via O-PLANCORPUS |
| O-PLANCORPUS corpus gate | fail if known-RED goes GREEN / known-GREEN goes RED | restrictive | Standing re-lint; requires live flag set incl. `--story-scope` |

## Grep harvest (review)

EOF

  echo "### plan-lint.py env / default markers"
  echo '```'
  _grepn 'environ\.get|os\.getenv|default |WARN tier|REQUIRE_SHAPE|SHAPE_WARN|story_deploy[[:space:]]*=' "$LINT" \
    | head -80
  echo '```'
  echo
  echo "### supervisor.sh \${VAR:-default} (guard-adjacent sample)"
  echo '```'
  _grepn 'Oracle|INFERABSENT|PLAN_LINT|STORY_DEPLOY|STORY_SCOPE|WORKER_FIRST|:-true|:-false|:-1|:-0|default present' "$SUP" \
    | head -80
  echo '```'
  echo
  cat <<'EOF'
## Classification guide

- **permissive:** a missing declaration lets work proceed (WARN, default
  present, soft fixture grandfather, retest deferred).
- **restrictive:** a missing declaration blocks (HARD RED, skip worker,
  HOLD, dispose tip).

Fail-open defaults remaining are the Wave4 §2 work list. §2.1/§2.2 closed:
Oracle derived (O-ORACLEDERIVE); O-INFERABSENT LINT with O-NULLACTION-shaped
proceed — prefer reshape over adding incident-named conditionals.

EOF
  echo "_Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
} > "$tmp"

# O-DEFAULTRG — refuse empty harvest before GREEN (generate + --check).
assert_fence_harvest "$tmp" || {
  rm -f "$tmp"
  exit 1
}

if [ "$CHECK" = "1" ]; then
  if [ ! -f "$OUT" ]; then
    echo "O-DEFAULTAUDIT: missing $OUT — run without --check to generate" >&2
    rm -f "$tmp"
    exit 1
  fi
  # Seed table must remain; grep body may drift — require seed rows present.
  for needle in 'O-INFERABSENT' 'Oracle field' 'PLAN_LINT_REQUIRE_SHAPE' 'Retest-owed' 'O-PLANCORPUS' 'O-ORACLEDERIVE' 'Proceed: O-NULLACTION'; do
    grep -q "$needle" "$OUT" || {
      echo "O-DEFAULTAUDIT: artefact missing seed row: $needle" >&2
      rm -f "$tmp"
      exit 1
    }
  done
  # §2.1/§2.2 closed — refuse stale permissive seed text
  if grep -q 'WARN tier (does not fail PLAN OK)' "$OUT"; then
    echo "O-DEFAULTAUDIT: stale O-INFERABSENT WARN-tier seed — regenerate" >&2
    rm -f "$tmp"
    exit 1
  fi
  if grep -q 'present` when field absent' "$OUT" || grep -q 'else "present"' "$OUT"; then
    echo "O-DEFAULTAUDIT: stale Oracle default-present seed — regenerate" >&2
    rm -f "$tmp"
    exit 1
  fi
  # O-DEFAULTRG — artefact harvest fences must also be non-empty
  assert_fence_harvest "$OUT" || {
    rm -f "$tmp"
    exit 1
  }
  echo "O-DEFAULTAUDIT: artefact seed rows OK ($OUT)"
  rm -f "$tmp"
  exit 0
fi

mv "$tmp" "$OUT"
echo "O-DEFAULTAUDIT: wrote $OUT"
# Count permissive vs restrictive in the seed table
perm=$(grep -c '| permissive' "$OUT" || true)
rest=$(grep -c '| restrictive' "$OUT" || true)
echo "O-DEFAULTAUDIT: seed classification permissive≈$perm restrictive≈$rest"
exit 0
