#!/usr/bin/env python3
"""K6 — derive destination pre-satisfied rules after M1 dest-baseline kantra.

Compares migration/mta-findings.json (legacy) vs mta-findings-dest-baseline.json
(pristine modernized). A legacy rule absent from the dest scan is pre-satisfied
ONLY when its incidents are pom/props or every incident basename already exists
under src/ — never when Java work simply has not been harvested yet
(O-DELTABASE / ABSENT-NOT-LANDED).

Writes migration/scaffold-presatisfied.generated.txt (merged with static list
by plan-lint / oracle readers).

Usage: dest-presatisfied.py [legacy.json] [dest-baseline.json]
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(os.environ.get("ORACLE_ROOT", ".")).resolve()


def load_rules(path: Path) -> dict[str, dict]:
    if not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, dict] = {}
    for rs in data:
        for rid, v in (rs.get("violations") or {}).items():
            out[rid] = v
    return out


def basenames(v: dict) -> list[str]:
    names = []
    for inc in v.get("incidents") or []:
        uri = unquote(inc.get("uri") or "")
        if uri.startswith("file:"):
            uri = urlparse(uri).path or uri
        b = Path(uri).name
        if b and b != "?":
            names.append(b)
    return names


def in_src(name: str) -> bool:
    for rel in ("src/main", "src/test"):
        d = ROOT / rel
        if d.is_dir() and any(d.rglob(name)):
            return True
    return False


def is_config(name: str) -> bool:
    return name == "pom.xml" or name.endswith((".properties", ".yaml", ".yml", ".xml"))


def main() -> int:
    legacy_p = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "migration/mta-findings.json"
    dest_p = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else ROOT / "migration/mta-findings-dest-baseline.json"
    )
    legacy, dest = load_rules(legacy_p), load_rules(dest_p)
    if not legacy or not dest_p.is_file():
        print("dest-presatisfied: skip (missing inputs)")
        return 0
    generated: list[str] = []
    for rid, v in sorted(legacy.items()):
        if rid in dest:
            continue
        names = basenames(v)
        if not names:
            continue
        if all(is_config(n) for n in names):
            generated.append(rid)
            continue
        if all(is_config(n) or in_src(n) for n in names):
            generated.append(rid)
    out = ROOT / "migration/scaffold-presatisfied.generated.txt"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by dest-presatisfied.py (K6) — do not hand-edit",
        "# Legacy rules absent from pristine dest-baseline with landed/config evidence",
        *generated,
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"dest-presatisfied: wrote {len(generated)} rules → {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
