#!/usr/bin/env python3
"""K4 — emit custom kantra rules from migration.yaml contract fields.

Parameterized (migration-general): preserve:/forbidden:/acceptance.path
plus a static ExceptionMapper<Exception> forbid. Sensors remain defense
in depth; these rules put the same contracts into mta-findings.json at M1
so K1 ownership / K5 delta / M5 evaluate see them.

Usage:
  gen-contract-rules.py [--yaml migration.yaml] [--out .hermes/rules/generated-contract-rules.yaml]
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover — stdlib fallback
    yaml = None


def _slug(s: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", s.strip()).strip("-").lower()
    return (s or "item")[:48]


def _parse_simple(text: str) -> dict:
    """Minimal YAML subset when PyYAML is unavailable (lists under keys)."""
    data: dict = {"preserve": [], "forbidden": [], "acceptance": {}}
    section = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if re.match(r"^preserve:\s*$", line):
            section = "preserve"
            continue
        if re.match(r"^forbidden:\s*$", line):
            section = "forbidden"
            continue
        if re.match(r"^acceptance:\s*$", line):
            section = "acceptance"
            continue
        if re.match(r"^[a-zA-Z]", line) and not line.startswith(" "):
            section = None
            continue
        if section in ("preserve", "forbidden"):
            m = re.match(r"^\s*-\s+(.*)$", line)
            if m:
                val = m.group(1).strip().strip("\"'")
                data[section].append(val)
        if section == "acceptance":
            m = re.match(r"^\s*([A-Za-z][A-Za-z0-9_]*)\s*:\s*(\S+)", line)
            if m:
                data["acceptance"][m.group(1)] = m.group(2).strip().strip("\"'")
    return data


def load_migration(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        doc = yaml.safe_load(text) or {}
        return {
            "preserve": list(doc.get("preserve") or []),
            "forbidden": list(doc.get("forbidden") or []),
            "acceptance": dict(doc.get("acceptance") or {}),
        }
    return _parse_simple(text)


def emit_rules(contract: dict) -> str:
    rules: list[str] = [
        "# GENERATED by gen-contract-rules.py (K4) — do not hand-edit.",
        "# Source: migration.yaml preserve:/forbidden:/acceptance.",
        "",
    ]
    for key in contract.get("preserve") or []:
        if not key or not isinstance(key, str):
            continue
        rid = f"demo-preserve-{_slug(key)}-00001"
        pat = re.escape(key)
        rules.append(
            f"""- ruleID: {rid}
  category: mandatory
  effort: 3
  description: Preserve contract key {key} must remain env-driven
  message: >
    migration.yaml preserve: lists `{key}`. Keep this token env-driven in
    application properties / k8s env (not hardcoded away). Plan-lint and
    sensors also enforce; this rule owns the finding at M1.
  labels:
    - konveyor.io/target=quarkus
  when:
    builtin.filecontent:
      filePattern: ".*(application[^/]*\\\\.(properties|ya?ml)|.*\\\\.ya?ml)$"
      pattern: "{pat}"
"""
        )
    for pat_raw in contract.get("forbidden") or []:
        if not pat_raw or not isinstance(pat_raw, str):
            continue
        rid = f"demo-forbidden-{_slug(pat_raw)}-00001"
        pat = re.escape(pat_raw)
        rules.append(
            f"""- ruleID: {rid}
  category: mandatory
  effort: 5
  description: Forbidden fabrication pattern {pat_raw}
  message: >
    migration.yaml forbidden: lists `{pat_raw}`. Do not introduce this
    stand-in into src/main — sensors fail the commit; this rule surfaces
    it in M1 findings for task ownership.
  labels:
    - konveyor.io/target=quarkus
  when:
    builtin.filecontent:
      filePattern: ".*\\\\.java$"
      pattern: "{pat}"
"""
        )
    # Static: ExceptionMapper<Exception> (V6 R6) — always emit.
    rules.append(
        """- ruleID: demo-forbidden-exception-mapper-00001
  category: mandatory
  effort: 3
  description: ExceptionMapper<Exception> remaps NotFound to 503
  message: >
    Narrow ExceptionMapper to catalog/service failures — never
    ExceptionMapper<Exception>. Sensors enforce (V6 R6); this rule puts
    the contract in mta-findings for planning ownership.
  labels:
    - konveyor.io/target=quarkus
  when:
    builtin.filecontent:
      filePattern: ".*\\\\.java$"
      pattern: "ExceptionMapper\\\\s*<\\\\s*Exception\\\\s*>"
"""
    )
    acc_block = contract.get("acceptance") or {}
    acc = acc_block.get("path")
    collection = acc_block.get("collection") or "products"
    if acc:
        leaf = acc.rstrip("/").split("/")[-1]
        rules.append(
            f"""- ruleID: demo-acceptance-surface-00001
  category: mandatory
  effort: 3
  description: Acceptance path {acc} must have a real handler surface
  message: >
    migration.yaml acceptance.path is `{acc}` (collection `{collection}`).
    Plan a task that implements the handler (leaf `{leaf}` / acceptanceCheck)
    with a live collection-backed proof — not a ceremonial status map.
    Sensors enforce at ship (O-ACCEPTGEN); this rule owns planning-time visibility.
  labels:
    - konveyor.io/target=quarkus
  when:
    or:
      - builtin.filecontent:
          filePattern: ".*\\\\.java$"
          pattern: "acceptanceCheck|acceptance-check|{re.escape(leaf)}"
      - builtin.filecontent:
          filePattern: ".*migration\\\\.ya?ml$"
          pattern: "acceptance:"
"""
        )
    return "\n".join(rules).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", default="migration.yaml")
    ap.add_argument("--out", default=".hermes/rules/generated-contract-rules.yaml")
    args = ap.parse_args()
    src = Path(args.yaml)
    if not src.is_file():
        print(f"gen-contract-rules: no {src} — skip")
        return 0
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = emit_rules(load_migration(src))
    out.write_text(text, encoding="utf-8")
    n = text.count("ruleID:")
    print(f"gen-contract-rules: wrote {n} rules → {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
