#!/usr/bin/env python3
"""ADR-24 — Migration Model: typed single source of truth.

Generated by M1 (`emit`); story assignment via `assign_stories` (sole M2 writer).
Harness consumers join on unit keys / target_path — never basename greps of
migration markdown.

CLI:
  model.py emit [--legacy DIR] [--root DIR]
  model.py assign-stories [--root DIR]
  model.py context-for <SID> [--root DIR]
  model.py lint-scc-atomic <tasks.md> <SID> [--root DIR]
  model.py lint-finding-kind <tasks.md> [--root DIR]   # F9
  model.py story-complete <SID> [--root DIR]
  model.py cover-check [--root DIR]   # F8 staging coverage
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# Load hyphenated dependency-order.py (cannot `import dependency_order`).
_HARNESS = Path(__file__).resolve().parent
import importlib.util

_spec = importlib.util.spec_from_file_location(
    "dependency_order", _HARNESS / "dependency-order.py"
)
dependency_order = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(dependency_order)


MODEL_REL = Path("migration/model.json")
ALLOWLIST_REL = Path(".hermes/harness/migration-model-allowlist.txt")


def _utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _git_head(root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _read_packages(root: Path) -> tuple[str, str]:
    yml = root / "migration.yaml"
    text = yml.read_text(encoding="utf-8", errors="replace") if yml.is_file() else ""
    lm = re.search(r"legacyPackage:\s*([\w.]+)", text)
    tm = re.search(r"targetPackage:\s*([\w.]+)", text)
    return (
        lm.group(1) if lm else "com.example.legacy",
        tm.group(1) if tm else "com.demo",
    )


def _remap_fqn(legacy_fqn: str, legacy_pkg: str, target_pkg: str) -> str:
    if legacy_fqn.startswith(legacy_pkg + ".") or legacy_fqn == legacy_pkg:
        return target_pkg + legacy_fqn[len(legacy_pkg) :]
    # Fall back: keep simple name under target root package leaf
    simple = legacy_fqn.rsplit(".", 1)[-1]
    # Preserve relative package suffix after common root when possible
    parts = legacy_fqn.split(".")
    if len(parts) >= 2:
        # Preserve trailing layer segment (model/repository/service/…) under target.
        for i, p in enumerate(parts):
            if p in ("model", "repository", "service", "rest", "util", "mapper"):
                return target_pkg + "." + ".".join(parts[i:])
    return f"{target_pkg}.{simple}"


def _path_for_fqn(fqn: str) -> str:
    return "src/main/java/" + fqn.replace(".", "/") + ".java"


def condensation_order(analysis: dict) -> tuple[list[str], dict[int, str]]:
    """Unit keys or SCC ids — never flattened multi-member SCCs (ADR-24 §2.1)."""
    imports = analysis["imports"]
    fan_in = analysis["fan_in"]
    sccs = analysis["sccs"]
    fqn_scc: dict[str, int] = {}
    for i, comp in enumerate(sccs):
        for f in comp:
            fqn_scc[f] = i
    succ: dict[int, set[int]] = {i: set() for i in range(len(sccs))}
    pred_count = {i: 0 for i in range(len(sccs))}
    for fqn, deps in imports.items():
        a = fqn_scc.get(fqn)
        if a is None:
            continue
        for d in deps:
            b = fqn_scc.get(d)
            if b is None or b == a:
                continue
            if a not in succ[b]:
                succ[b].add(a)
                pred_count[a] += 1
    ready = sorted(
        (i for i in range(len(sccs)) if pred_count[i] == 0),
        key=lambda i: (-max((fan_in[f] for f in sccs[i]), default=0), min(sccs[i])),
    )
    order: list[str] = []
    seen: set[int] = set()
    scc_id_of: dict[int, str] = {}
    multi_n = 0
    for i, comp in enumerate(sccs):
        if len(comp) > 1:
            multi_n += 1
            scc_id_of[i] = f"SCC-{multi_n}"
    while ready:
        i = ready.pop(0)
        if i in seen:
            continue
        seen.add(i)
        if len(sccs[i]) == 1:
            order.append(sccs[i][0])
        else:
            order.append(scc_id_of[i])
        for a in sorted(succ.get(i, ()), key=lambda j: (min(sccs[j]), j)):
            pred_count[a] -= 1
            if pred_count[a] == 0:
                ready.append(a)
        ready.sort(
            key=lambda j: (
                -max((fan_in[f] for f in sccs[j]), default=0),
                min(sccs[j]),
            )
        )
    for i, comp in enumerate(sccs):
        if i not in seen:
            if len(comp) == 1:
                order.append(comp[0])
            else:
                order.append(scc_id_of[i])
    return order, scc_id_of


def build_model(
    root: Path,
    legacy_root: Path,
    *,
    preserve_stories: Optional[list[dict]] = None,
) -> dict[str, Any]:
    legacy_pkg, target_pkg = _read_packages(root)
    analysis = dependency_order.analyze(str(legacy_root))
    classes = analysis["classes"]
    imports = analysis["imports"]
    fan_in = analysis["fan_in"]
    cycles = analysis["cycles"]
    order, scc_id_of = condensation_order(analysis)

    fqn_to_scc: dict[str, str] = {}
    sccs_out: list[dict] = []
    for i, comp in enumerate(analysis["sccs"]):
        if len(comp) <= 1:
            continue
        sid = scc_id_of[i]
        members = sorted(comp)
        for m in members:
            fqn_to_scc[m] = sid
        # cycle edge labels (undirected pairs among members that import each other)
        cycle_edges: list[str] = []
        for a in members:
            for b in imports.get(a, ()):
                if b in fqn_to_scc and fqn_to_scc[b] == sid and a < b:
                    cycle_edges.append(f"{a.rsplit('.',1)[-1]}<->{b.rsplit('.',1)[-1]}")
        sccs_out.append({"id": sid, "members": members, "cycles": sorted(set(cycle_edges))})

    # O-ADR24FIND: Findings IR is the only findings identity input.
    import findings_ir

    ir = findings_ir.ensure_ir(root)

    units: list[dict] = []
    for fqn, rel in sorted(classes.items()):
        # dependency-order paths are relative to legacy root (often already src/...)
        legacy_path = rel if rel.startswith("src/") else f"src/main/java/{rel}"
        # normalize when analyze walked from legacy root containing src/
        if not legacy_path.startswith("src/") and "/src/" in rel:
            legacy_path = rel[rel.index("src/") :]
        target_fqn = _remap_fqn(fqn, legacy_pkg, target_pkg)
        target_path = _path_for_fqn(target_fqn)
        staging_path = f"migration/staging/{legacy_path}"
        alt = root / "migration" / "staging" / legacy_path
        if alt.is_file():
            staging_path = str(alt.relative_to(root))
        elif (root / staging_path).is_file():
            pass

        units.append(
            {
                "key": fqn,
                "kind": "java",
                "legacy_fqn": fqn,
                "legacy_path": legacy_path,
                "target_fqn": target_fqn,
                "target_path": target_path,
                "staging_path": staging_path,
                "scc": fqn_to_scc.get(fqn),
                "depends_on": sorted(imports.get(fqn, ())),
                "fan_in": int(fan_in.get(fqn, 0)),
                "fan_out": len(imports.get(fqn, ())),
                "findings": [],
            }
        )

    # Non-java structural seeds from common migration paths (ADR-24 §2.7)
    for rel, kind in (
        ("pom.xml", "pom"),
        ("src/main/resources/application.properties", "resources"),
        ("src/main/resources/application.yml", "resources"),
    ):
        lp = legacy_root / rel
        if lp.is_file():
            key = f"coord:{rel}"
            units.append(
                {
                    "key": key,
                    "kind": kind,
                    "legacy_fqn": None,
                    "legacy_path": rel,
                    "target_fqn": None,
                    "target_path": rel,
                    "staging_path": f"migration/staging/{rel}",
                    "scc": None,
                    "depends_on": [],
                    "fan_in": 0,
                    "fan_out": 0,
                    "findings": [],
                }
            )

    # Also seed resource units referenced by IR incidents (properties etc.)
    known_lp = {u.get("legacy_path") for u in units}
    for rule in ir.get("rules") or []:
        for inc in rule.get("incidents") or []:
            lp = (inc.get("legacy_path") or "").strip()
            if not lp or lp in known_lp:
                continue
            if lp.endswith(".java"):
                continue  # java must come from class graph
            kind = findings_ir.infer_kind(lp)
            key = f"coord:{lp}"
            units.append(
                {
                    "key": key,
                    "kind": kind,
                    "legacy_fqn": None,
                    "legacy_path": lp,
                    "target_fqn": None,
                    "target_path": lp,
                    "staging_path": f"migration/staging/{lp}",
                    "scc": None,
                    "depends_on": [],
                    "fan_in": 0,
                    "fan_out": 0,
                    "findings": [],
                }
            )
            known_lp.add(lp)

    findings, units, unbound = findings_ir.bind_findings_to_units(ir, units)
    bind_reds = findings_ir.lint_bind_closed(ir, findings)
    # ADR-25 / F-unbound-zero: pristine input ⇒ unbound must be empty (no waivers)
    bind_reds.extend(findings_ir.lint_unbound_zero(unbound))

    prov = ir.get("provenance") or {}
    model: dict[str, Any] = {
        "provenance": {
            "producer": "m1",
            "source_sha": _git_head(legacy_root if (legacy_root / ".git").exists() else root),
            "findings_sha256": prov.get("source_sha256") or "",
            "findings_ir_sha256": prov.get("ir_sha256") or "",
            "legacy_package": legacy_pkg,
            "target_package": target_pkg,
            "tool_versions": {"dependency_order": "adr24", "findings_ir": "v1"},
            "generated_at": _utc(),
            "findings_unbound": unbound[:50],
            "findings_bind_reds": bind_reds,
        },
        "units": units,
        "sccs": sccs_out,
        "order": order,
        "findings": findings,
        "stories": preserve_stories if preserve_stories is not None else [],
    }
    model["_cycles_count"] = len(cycles)
    model["_bind_reds"] = bind_reds
    return model


def load(root: Path) -> dict[str, Any]:
    path = root / MODEL_REL
    if not path.is_file():
        raise FileNotFoundError(f"missing {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def save(root: Path, model: dict[str, Any]) -> Path:
    path = root / MODEL_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    # strip private keys
    out = {k: v for k, v in model.items() if not k.startswith("_")}
    path.write_text(json.dumps(out, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    return path


def unit_by_key(model: dict, key: str) -> Optional[dict]:
    for u in model.get("units") or []:
        if u.get("key") == key:
            return u
    return None


def units_for_story(model: dict, sid: str) -> list[dict]:
    for st in model.get("stories") or []:
        if st.get("id") == sid:
            keys = set(st.get("units") or [])
            return [u for u in model.get("units") or [] if u.get("key") in keys]
    return []


def scc_of(model: dict, key: str) -> Optional[dict]:
    u = unit_by_key(model, key)
    if not u or not u.get("scc"):
        return None
    for s in model.get("sccs") or []:
        if s.get("id") == u["scc"]:
            return s
    return None


def order_for_story(model: dict, sid: str) -> list[str]:
    keys = {u["key"] for u in units_for_story(model, sid)}
    if not keys:
        return list(model.get("order") or [])
    scc_ids = {
        u["scc"]
        for u in units_for_story(model, sid)
        if u.get("scc")
    }
    out: list[str] = []
    for item in model.get("order") or []:
        if item in keys or item in scc_ids:
            out.append(item)
    return out


def context_for(model: dict, sid: str) -> str:
    """Structured M3 projection — no markdown scrape, no silent cap (ADR-24 G4)."""
    units = units_for_story(model, sid)
    if not units and not (model.get("stories") or []):
        # Pre-assign_stories: project by matching nothing — caller may pass scope
        units = list(model.get("units") or [])
    lines = [
        "===== BEGIN DERIVED FACTS (authoritative — ADR-24 model projection) =====",
        "O-M3DERIVEDCTX: where BRIEF and DERIVED FACTS disagree, DERIVED FACTS win.",
        f"story: {sid}",
        f"units ({len(units)}):",
    ]
    for u in units:
        if u.get("kind") != "java":
            lines.append(
                f"  - [{u.get('kind')}] {u.get('target_path')} <- {u.get('legacy_path')}"
            )
            continue
        scc = u.get("scc") or "-"
        fids = ",".join(u.get("findings") or []) or "-"
        lines.append(
            f"  - {u.get('target_fqn')} <- {u.get('legacy_fqn')}  scc={scc}  findings=[{fids}]"
        )
    # convert-together batches intersecting this story
    unit_keys = {u["key"] for u in units}
    for scc in model.get("sccs") or []:
        members = set(scc.get("members") or [])
        if not members & unit_keys:
            continue
        simples = [m.rsplit(".", 1)[-1] for m in scc.get("members") or []]
        cycles = ", ".join(scc.get("cycles") or []) or "cyclic"
        lines.append(
            f"convert-together: {scc['id']} = {{{', '.join(simples)}}}  ({cycles}) — ONE task"
        )
    ord_items = order_for_story(model, sid)
    if ord_items:
        pretty = []
        for i, item in enumerate(ord_items, 1):
            if item.startswith("SCC-"):
                scc = next((s for s in model.get("sccs") or [] if s["id"] == item), None)
                if scc:
                    names = ",".join(m.rsplit(".", 1)[-1] for m in scc["members"])
                    pretty.append(f"{i} {item}{{{names}}}")
                else:
                    pretty.append(f"{i} {item}")
            else:
                pretty.append(f"{i} {item.rsplit('.', 1)[-1]}")
        lines.append("order: " + " · ".join(pretty))
    lines.append("===== END DERIVED FACTS =====")
    return "\n".join(lines)


def context_for_scope(model: dict, scope_paths: list[str]) -> str:
    """Projection before stories[] is bound — select units by exact legacy_path ∈ scope.

    O-ADR24BASENAME: no Path(...).name / suffix joins — scope must list full paths
    (or exact prefixes only when the scope entry itself is a directory path ending /).
    """
    scope = {p.strip().rstrip("/") for p in scope_paths if p.strip()}
    selected = []
    for u in model.get("units") or []:
        lp = (u.get("legacy_path") or "").strip()
        if not lp:
            continue
        if lp in scope:
            selected.append(u)
            continue
        # directory scopes: exact prefix with path boundary (not basename)
        for sp in scope:
            if sp.endswith(".java") or "." in Path(sp).name:
                continue
            if lp.startswith(sp.rstrip("/") + "/"):
                selected.append(u)
                break
    # Build a temporary story view
    tmp = dict(model)
    tmp["stories"] = [
        {
            "id": "SCOPE",
            "units": [u["key"] for u in selected],
            "findings": [],
            "deploy": False,
        }
    ]
    return context_for(tmp, "SCOPE").replace("story: SCOPE", "story: (scope projection)")


def assign_stories(root: Path, model: Optional[dict] = None) -> dict:
    """M2 sole mutation: fill stories[] from roadmap — total, disjoint, SCC-atomic."""
    model = model or load(root)
    roadmap = root / "migration" / "roadmap.md"
    if not roadmap.is_file():
        raise FileNotFoundError("migration/roadmap.md required for assign_stories")
    text = roadmap.read_text(encoding="utf-8", errors="replace")
    blocks = re.split(r"(?m)^##\s+(S\d+)\b", text)
    # blocks: [pre, S01, body1, S02, body2, ...]
    stories: list[dict] = []
    claimed: dict[str, str] = {}
    units_by_legacy_path = {
        u.get("legacy_path"): u for u in model.get("units") or [] if u.get("legacy_path")
    }
    units_by_key = {u["key"]: u for u in model.get("units") or []}

    for i in range(1, len(blocks), 2):
        sid = blocks[i]
        body = blocks[i + 1] if i + 1 < len(blocks) else ""
        sm = re.search(r"(?im)^-\s*slug:\s*(\S+)", body)
        slug = sm.group(1) if sm else sid
        dm = re.search(r"(?im)^-\s*deploy:\s*(true|false)", body)
        deploy = bool(dm and dm.group(1).lower() == "true")
        scm = re.search(r"(?im)^-\s*scope:\s*(.+)$", body)
        scope_raw = scm.group(1).strip() if scm else ""
        paths = [p.strip() for p in re.split(r"[\s,]+", scope_raw) if p.strip()]
        unit_keys: list[str] = []
        for p in paths:
            # O-ADR24BASENAME: exact legacy_path / coord key only — no basename join.
            u = units_by_legacy_path.get(p)
            if u is None:
                key = f"coord:{p}"
                if key in units_by_key:
                    u = units_by_key[key]
            if u is None:
                continue
            k = u["key"]
            if k in claimed and claimed[k] != sid:
                raise SystemExit(
                    f"O-ADR24 assign_stories RED: unit {k} dual-owned by "
                    f"{claimed[k]} and {sid}"
                )
            claimed[k] = sid
            if k not in unit_keys:
                unit_keys.append(k)

        # SCC-indivisible at M2: claiming any member claims the whole SCC into
        # this story; refuse only when members are already claimed elsewhere (F7).
        for scc in model.get("sccs") or []:
            members = scc.get("members") or []
            hit = [m for m in members if m in unit_keys]
            if not hit:
                continue
            for m in members:
                if m in claimed and claimed[m] != sid:
                    raise SystemExit(
                        f"O-ADR24 assign_stories RED: {scc['id']} spans "
                        f"{claimed[m]} and {sid} (F7)"
                    )
                claimed[m] = sid
                if m not in unit_keys:
                    unit_keys.append(m)

        fids: list[str] = []
        for k in unit_keys:
            fids.extend(units_by_key.get(k, {}).get("findings") or [])
        stories.append(
            {
                "id": sid,
                "slug": slug,
                "units": unit_keys,
                "findings": sorted(set(fids)),
                "deploy": deploy,
            }
        )

    # Total + disjoint: every java unit assigned exactly once.
    all_java = {
        u["key"] for u in model.get("units") or [] if u.get("kind") == "java"
    }
    orphans = sorted(all_java - set(claimed))
    if orphans:
        raise SystemExit(
            f"O-ADR24 assign_stories RED: {len(orphans)} unassigned java unit(s) "
            f"(total invariant): {orphans[:8]}"
        )

    model["stories"] = stories
    model.setdefault("provenance", {})["stories_assigned_at"] = _utc()
    save(root, model)
    return model


def lint_scc_atomic(model: dict, tasks_text: str, sid: str) -> list[str]:
    """M3: each intersecting SCC owned by exactly one task (ADR-24 §2.6)."""
    reds: list[str] = []
    story_units = {u["key"] for u in units_for_story(model, sid)}
    if not story_units:
        return reds
    # parse tasks
    heads = list(
        re.finditer(
            r"^(#{2,6})\s+(T[-A-Za-z0-9]*\d+[A-Za-z]*)\s*:\s*(.+)$",
            tasks_text,
            re.M,
        )
    )
    task_bodies: list[tuple[str, str]] = []
    for i, m in enumerate(heads):
        start = m.end()
        end = heads[i + 1].start() if i + 1 < len(heads) else len(tasks_text)
        task_bodies.append((m.group(2), tasks_text[start:end]))

    def task_owns(body: str) -> set[str]:
        paths = set(
            re.findall(
                r"(?im)^\s*\*?\*?(?:Owns|Absorbs|Target(?:\s*design)?)\*?\*?\s*:\s*`?([^`\n]+)`?",
                body,
            )
        )
        # also arrow targets
        paths.update(re.findall(r"src/(?:main|test)/java/[A-Za-z0-9_./]+\.java", body))
        keys: set[str] = set()
        batch = re.search(r"(?i)shape:\s*batch:(SCC-\d+)", body)
        if batch:
            scc = next(
                (s for s in model.get("sccs") or [] if s["id"] == batch.group(1)),
                None,
            )
            if scc:
                keys.update(scc.get("members") or [])
        for u in model.get("units") or []:
            tp = u.get("target_path") or ""
            lp = u.get("legacy_path") or ""
            for raw in paths:
                parts = raw.strip().split()
                if not parts:
                    continue
                p = parts[0].strip("`")
                if not p:
                    continue
                # O-ADR24BASENAME: exact Owns/Target paths only.
                if tp and p == tp:
                    keys.add(u["key"])
                if lp and p == lp:
                    keys.add(u["key"])
        return keys

    for scc in model.get("sccs") or []:
        members = set(scc.get("members") or [])
        if not members <= story_units:
            if members & story_units:
                reds.append(
                    f"LINT:scc-atomic: {scc['id']} intersects {sid} but not fully "
                    f"assigned to the story (M2 invariant broken)"
                )
            continue
        owners = []
        for tid, body in task_bodies:
            owned = task_owns(body)
            if members <= owned or re.search(
                rf"(?i)shape:\s*batch:{re.escape(scc['id'])}", body
            ):
                owners.append(tid)
        if len(owners) != 1:
            reds.append(
                f"LINT:scc-atomic: {scc['id']} must be owned by exactly one task; "
                f"found {len(owners)} ({', '.join(owners) or 'none'})"
            )
    return reds


def path_tracked(root: Path, rel: str) -> bool:
    try:
        subprocess.check_output(
            ["git", "-C", str(root), "cat-file", "-e", f"HEAD:{rel}"],
            stderr=subprocess.DEVNULL,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return (root / rel).is_file()


def story_complete(root: Path, model: dict, sid: str) -> tuple[bool, list[str]]:
    """F5: targets present AND story findings not REMAINING in findings-delta."""
    reasons: list[str] = []
    units = units_for_story(model, sid)
    if not units:
        return False, [f"no units bound for {sid}"]
    for u in units:
        tp = u.get("target_path")
        if not tp:
            continue
        if u.get("kind") == "remove":
            if path_tracked(root, tp):
                reasons.append(f"remove target still present: {tp}")
            continue
        if not path_tracked(root, tp):
            reasons.append(f"missing target: {tp}")
    story_fids: list[str] = []
    for st in model.get("stories") or []:
        if st.get("id") == sid:
            story_fids = list(st.get("findings") or [])
            break
    if not story_fids:
        for u in units:
            story_fids.extend(u.get("findings") or [])
        story_fids = sorted(set(story_fids))
    delta = root / "migration" / "findings-delta.txt"
    if delta.is_file() and story_fids:
        dtxt = delta.read_text(encoding="utf-8", errors="replace")
        for fid in story_fids:
            if re.search(
                rf"(?i)(REMAINING|ABSENT-NOT-LANDED).*{re.escape(fid)}"
                rf"|{re.escape(fid)}.*(REMAINING|ABSENT-NOT-LANDED)",
                dtxt,
            ):
                reasons.append(f"finding undischarged: {fid}")
    elif story_fids and not delta.is_file():
        # Fail-closed when findings exist but delta never produced (S01-shaped lie).
        reasons.append("findings-delta.txt absent while story has findings (F5)")
    return (len(reasons) == 0), reasons


def cover_check(root: Path, model: dict) -> list[str]:
    """F8: model covers staging **main** .java (exact path — O-ADR24BASENAME).

    Policy (Wave5 W5-003/W5-005): test sources are out of F8 scope unless a unit
    explicitly owns a src/test path. cover_check must agree with that intent
    (no silent rc=1 on tests).
    """
    errs: list[str] = []
    staging = root / "migration" / "staging"
    if not staging.is_dir():
        return errs
    covered_rels: set[str] = set()
    for u in model.get("units") or []:
        sp = u.get("staging_path") or ""
        lp = u.get("legacy_path") or ""
        if sp:
            covered_rels.add(sp)
        if lp:
            covered_rels.add(f"migration/staging/{lp}")
    for p in staging.rglob("*.java"):
        rel = str(p.relative_to(root))
        # Default F8 scope = main production sources only.
        if "/src/test/" in rel.replace("\\", "/"):
            continue
        if rel in covered_rels:
            continue
        errs.append(f"uncovered staging java: {rel}")
    return errs


def _task_bodies(tasks_text: str) -> list[tuple[str, str]]:
    heads = list(
        re.finditer(
            r"^(#{2,6})\s+(T[-A-Za-z0-9]*\d+[A-Za-z]*)\s*:\s*(.+)$",
            tasks_text,
            re.M,
        )
    )
    out: list[tuple[str, str]] = []
    for i, m in enumerate(heads):
        start = m.end()
        end = heads[i + 1].start() if i + 1 < len(heads) else len(tasks_text)
        out.append((m.group(2), tasks_text[start:end]))
    return out


def _task_owned_kinds(model: dict, body: str) -> set[str]:
    """Kinds of model units owned by a task (Owns/Target/batch:SCC)."""
    paths = set(
        re.findall(
            r"(?im)^\s*\*?\*?(?:Owns|Absorbs|Target(?:\s*design)?)\*?\*?\s*:\s*`?([^`\n]+)`?",
            body,
        )
    )
    paths.update(re.findall(r"src/(?:main|test)/java/[A-Za-z0-9_./]+\.java", body))
    keys: set[str] = set()
    batch = re.search(r"(?i)shape:\s*batch:(SCC-\d+)", body)
    if batch:
        scc = next(
            (s for s in model.get("sccs") or [] if s["id"] == batch.group(1)),
            None,
        )
        if scc:
            keys.update(scc.get("members") or [])
    for u in model.get("units") or []:
        tp = u.get("target_path") or ""
        lp = u.get("legacy_path") or ""
        for raw in paths:
            parts = raw.strip().split()
            if not parts:
                continue
            p = parts[0].strip("`")
            if not p:
                continue
            # O-ADR24BASENAME: exact Owns/Target paths only (same as task_owns).
            if tp and p == tp:
                keys.add(u["key"])
            if lp and p == lp:
                keys.add(u["key"])
    kinds: set[str] = set()
    by_key = {u["key"]: u for u in model.get("units") or []}
    for k in keys:
        u = by_key.get(k)
        if u:
            kinds.add(u.get("kind") or "java")
    # path-only ownership without unit match: infer from suffix
    for raw in paths:
        parts = raw.strip().split()
        if not parts:
            continue
        p = parts[0].strip("`")
        if p.endswith(".java"):
            kinds.add("java")
        elif p.endswith(".properties") or p.endswith(".yml") or p.endswith(".yaml"):
            kinds.add("resources")
        elif p.endswith("pom.xml") or p == "pom.xml":
            kinds.add("pom")
    return kinds


def lint_finding_kind(model: dict, tasks_text: str) -> list[str]:
    """F9: a finding on a java unit cannot be discharged by a non-java-only task."""
    reds: list[str] = []
    finding_kind = {
        f.get("id"): f.get("kind") or "java" for f in (model.get("findings") or [])
    }
    # also derive from unit bindings
    unit_kind = {u["key"]: u.get("kind") or "java" for u in model.get("units") or []}
    for f in model.get("findings") or []:
        for uk in f.get("units") or []:
            if unit_kind.get(uk) == "java":
                finding_kind[f["id"]] = "java"
    for tid, body in _task_bodies(tasks_text):
        fm = re.search(r"(?im)^\s*\*?\*?Findings\*?\*?\s*:\s*(.+)$", body)
        if not fm:
            continue
        raw = fm.group(1).strip()
        if not raw or raw.startswith("(none") or raw == "-":
            continue
        fids = [
            x.strip().strip("`")
            for x in re.split(r"[,;\s]+", raw)
            if x.strip() and re.match(r"^[a-z]", x.strip())
        ]
        owned_kinds = _task_owned_kinds(model, body)
        for fid in fids:
            if finding_kind.get(fid) != "java":
                continue
            if "java" not in owned_kinds:
                reds.append(
                    f"LINT:finding-kind: {tid} lists java finding {fid} but owns "
                    f"no java unit (kinds={sorted(owned_kinds) or ['none']}) (F9)"
                )
    return reds


def skeleton_condensation_units(model: dict, sid: str) -> list[dict]:
    """Required SCC skeleton preseed — one entry per condensation unit in story order.

    Each entry: {kind: scc|singleton, id, owns: [target_path...], members: [keys]}
    """
    units = {u["key"]: u for u in units_for_story(model, sid)}
    if not units:
        return []
    out: list[dict] = []
    seen: set[str] = set()
    for item in order_for_story(model, sid):
        if item.startswith("SCC-"):
            scc = next((s for s in model.get("sccs") or [] if s["id"] == item), None)
            if not scc:
                continue
            members = [m for m in (scc.get("members") or []) if m in units]
            if not members:
                continue
            owns = [
                units[m]["target_path"]
                for m in members
                if units[m].get("target_path")
            ]
            out.append(
                {
                    "kind": "scc",
                    "id": item,
                    "owns": owns,
                    "members": members,
                    "title": f"{item} convert-together — skeleton (fill from brief)",
                }
            )
            seen.update(members)
        elif item in units:
            u = units[item]
            out.append(
                {
                    "kind": "singleton",
                    "id": item,
                    "owns": [u["target_path"]] if u.get("target_path") else [],
                    "members": [item],
                    "title": f"{(u.get('target_fqn') or item).rsplit('.', 1)[-1]} — skeleton (fill from brief)",
                }
            )
            seen.add(item)
    # leftovers not in order (non-java etc.)
    for k, u in units.items():
        if k in seen:
            continue
        out.append(
            {
                "kind": "singleton",
                "id": k,
                "owns": [u["target_path"]] if u.get("target_path") else [],
                "members": [k],
                "title": f"{Path(u.get('target_path') or k).name} — skeleton (fill from brief)",
            }
        )
    return out


def render_dependency_order_md(model: dict) -> str:
    """One-way human view from the model (condensation order)."""
    units = {u["key"]: u for u in model.get("units") or [] if u.get("kind") == "java"}
    lines = [
        "# Legacy dependency analysis (scripted, M1 — ADR-24 view of model.json)",
        "",
        f"- Classes: {len(units)}; model order entries: {len(model.get('order') or [])}",
        "- Conversion order lists condensation units (SCC id or singleton) — not flattened SCC members.",
        "- O-M1SCC / ADR-24: circular groups are SCCs; convert together in ONE task.",
        "",
        "## God nodes (highest fan-in)",
        "",
        "| class | fan-in | fan-out |",
        "|---|---|---|",
    ]
    top = sorted(units.values(), key=lambda u: (-u.get("fan_in", 0), u["key"]))[:5]
    for u in top:
        lines.append(
            f"| {u['key']} | {u.get('fan_in', 0)} | {u.get('fan_out', 0)} |"
        )
    lines += ["", "## Conversion order (dependencies first — condensation units)", ""]
    for i, item in enumerate(model.get("order") or [], 1):
        if item.startswith("SCC-"):
            scc = next((s for s in model.get("sccs") or [] if s["id"] == item), None)
            if scc:
                members = ", ".join(
                    f"{m} ({units[m]['legacy_path']})" if m in units else m
                    for m in scc["members"]
                )
                lines.append(f"{i}. {item} — convert together: {members}")
            else:
                lines.append(f"{i}. {item}")
        else:
            u = units.get(item)
            if u:
                mark = " — god-node: characterization tests first" if u.get("fan_in", 0) >= 3 else ""
                lines.append(f"{i}. {item} ({u['legacy_path']}){mark}")
            else:
                lines.append(f"{i}. {item}")
    for scc in model.get("sccs") or []:
        lines += ["", f"## Circular group {scc['id']} (convert together in ONE task)", ""]
        for m in scc.get("members") or []:
            u = units.get(m)
            lines.append(f"- {m} ({u['legacy_path'] if u else '?'})")
    lines.append("")
    return "\n".join(lines)


def lint_stories_partition(model: dict) -> list[str]:
    """F-partition-total: if stories[] is non-empty, every demand-bearing unit
    is in exactly one story (W5-009 / O-ADR24PART).

    Demand-bearing = kind=java OR unit carries findings. Empty stories[] (M1
    pre-assign) is OK.
    """
    stories = model.get("stories") or []
    if not stories:
        return []
    reds: list[str] = []
    claimed: dict[str, str] = {}
    for s in stories:
        sid = s.get("id") or "?"
        for k in s.get("units") or []:
            if k in claimed:
                reds.append(
                    f"O-ADR24PART RED: unit {k} dual-owned by {claimed[k]} and {sid}"
                )
            else:
                claimed[k] = sid
    unit_by_key = {u["key"]: u for u in model.get("units") or []}
    for k in list(claimed):
        if k not in unit_by_key:
            reds.append(f"O-ADR24PART RED: ghost unit {k} in stories (not in units[])")
    must = {
        u["key"]
        for u in model.get("units") or []
        if u.get("kind") == "java" or (u.get("findings") or [])
    }
    missing = sorted(must - set(claimed))
    if missing:
        reds.append(
            f"O-ADR24PART RED: {len(missing)} demand-bearing unit(s) unassigned: "
            f"{missing[:8]}"
        )
    return reds


def cmd_emit(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    legacy = Path(args.legacy).resolve()
    prev_stories = None
    mp = root / MODEL_REL
    if mp.is_file() and not args.fresh_stories:
        try:
            prev_stories = load(root).get("stories") or []
        except Exception:
            prev_stories = None
    model = build_model(root, legacy, preserve_stories=prev_stories)
    bind_reds = list(model.pop("_bind_reds", []) or [])
    # W5-009: preserved partitions must still satisfy totality after unit-set change
    part_reds = lint_stories_partition(model)
    save(root, model)
    if bind_reds or part_reds:
        for r in bind_reds + part_reds:
            print(r, file=sys.stderr)
        print(
            "O-ADR24 emit RED: bind/partition invariant failed",
            file=sys.stderr,
        )
        return 1
    # one-way markdown view
    dep_md = root / "migration" / "dependency-order.md"
    # Preserve appended codegen/tag demand sections if present after marker
    prior_extra = ""
    if dep_md.is_file():
        old = dep_md.read_text(encoding="utf-8", errors="replace")
        # keep trailing sections that are not part of core render
        for marker in (
            "## Codegen demand",
            "## Tag demand",
            "O-CODEGENDEMAND",
            "O-TAGDEMAND",
        ):
            if marker in old:
                prior_extra = "\n" + old[old.index(marker) :]
                break
    core = render_dependency_order_md(model)
    # If we replaced conversion order with condensation, still allow appendices
    # from subsequent analyze.sh steps — those append after this write.
    dep_md.write_text(core + prior_extra, encoding="utf-8")
    errs = cover_check(root, model)
    if errs:
        print(f"O-ADR24 cover WARN: {len(errs)} staging gaps (F8)", file=sys.stderr)
        for e in errs[:10]:
            print(f"  {e}", file=sys.stderr)
    print(
        f"O-ADR24 emit: units={len(model['units'])} sccs={len(model['sccs'])} "
        f"order={len(model['order'])} → {MODEL_REL}"
    )
    return 0


def cmd_assign(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = assign_stories(root)
    print(
        f"O-ADR24 assign_stories: stories={len(model.get('stories') or [])} OK"
    )
    return 0


def cmd_context(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    if args.scope:
        scope = [p for p in re.split(r"[\s,]+", args.scope) if p]
        print(context_for_scope(model, scope))
    else:
        print(context_for(model, args.sid))
    return 0


def cmd_lint_scc(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    text = Path(args.tasks).read_text(encoding="utf-8", errors="replace")
    reds = lint_scc_atomic(model, text, args.sid)
    for r in reds:
        print(r)
    return 1 if reds else 0


def cmd_lint_finding_kind(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    text = Path(args.tasks).read_text(encoding="utf-8", errors="replace")
    reds = lint_finding_kind(model, text)
    for r in reds:
        print(r)
    return 1 if reds else 0


def cmd_story_complete(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    ok, reasons = story_complete(root, model, args.sid)
    if ok:
        print(f"story_complete {args.sid}: OK")
        return 0
    print(f"story_complete {args.sid}: RED")
    for r in reasons:
        print(f"  - {r}")
    return 1


def cmd_cover(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    errs = cover_check(root, model)
    for e in errs:
        print(e)
    return 1 if errs else 0


def main() -> int:
    ap = argparse.ArgumentParser(description="ADR-24 migration model")
    # Parent so `--root` works before or after the subcommand.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--root", default=".")
    sub = ap.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("emit", parents=[common])
    e.add_argument("--legacy", default="/projects/legacy")
    e.add_argument("--fresh-stories", action="store_true")
    e.set_defaults(func=cmd_emit)

    a = sub.add_parser("assign-stories", parents=[common])
    a.set_defaults(func=cmd_assign)

    c = sub.add_parser("context-for", parents=[common])
    c.add_argument("sid", nargs="?", default="")
    c.add_argument("--scope", default="")
    c.set_defaults(func=cmd_context)

    l = sub.add_parser("lint-scc-atomic", parents=[common])
    l.add_argument("tasks")
    l.add_argument("sid")
    l.set_defaults(func=cmd_lint_scc)

    fk = sub.add_parser("lint-finding-kind", parents=[common])
    fk.add_argument("tasks")
    fk.set_defaults(func=cmd_lint_finding_kind)

    s = sub.add_parser("story-complete", parents=[common])
    s.add_argument("sid")
    s.set_defaults(func=cmd_story_complete)

    k = sub.add_parser("cover-check", parents=[common])
    k.set_defaults(func=cmd_cover)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
