#!/usr/bin/env python3
"""ADR-24 — Migration Model: typed single source of truth.

Generated by M1 (`emit`); story assignment via `assign_stories` (sole M2 writer).
Harness consumers join on unit keys / target_path — never basename greps of
migration markdown.

CLI:
  model.py emit [--legacy DIR] [--root DIR]
  model.py assign-stories [--root DIR]
  model.py context-for <SID> [--root DIR]
  model.py context-for-profile [--root DIR] [--undecided-only] [--limit N]  # ADR-26 / O-PROF1OF79STOP
  model.py context-for-m2 [--root DIR]  # ADR-34 / F-no-discovery M2 projection
  model.py assign-tasks [--root DIR]    # ADR-35 typed model.tasks[]
  model.py render-tasks [--root DIR] [--sid SID]
  model.py emit-profile-skeleton [--root DIR] # ADR-27 §7 scaffolds before LLM
  model.py lint-scc-atomic <tasks.md> <SID> [--root DIR]
  model.py lint-finding-kind <tasks.md> [--root DIR]   # F9
  model.py story-complete <SID> [--root DIR]
  model.py cover-check [--root DIR]   # F8 staging coverage
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# Load hyphenated dependency-order.py (cannot `import dependency_order`).
_HARNESS = Path(__file__).resolve().parent
import importlib.util

_spec = importlib.util.spec_from_file_location(
    "dependency_order", _HARNESS / "dependency-order.py"
)
dependency_order = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(dependency_order)


MODEL_REL = Path("migration/model.json")
ALLOWLIST_REL = Path(".hermes/harness/migration-model-allowlist.txt")


def _utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _git_head(root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _read_packages(root: Path) -> tuple[str, str]:
    yml = root / "migration.yaml"
    text = yml.read_text(encoding="utf-8", errors="replace") if yml.is_file() else ""
    lm = re.search(r"legacyPackage:\s*([\w.]+)", text)
    tm = re.search(r"targetPackage:\s*([\w.]+)", text)
    return (
        lm.group(1) if lm else "com.example.legacy",
        tm.group(1) if tm else "com.demo",
    )


def _remap_fqn(legacy_fqn: str, legacy_pkg: str, target_pkg: str) -> str:
    if legacy_fqn.startswith(legacy_pkg + ".") or legacy_fqn == legacy_pkg:
        return target_pkg + legacy_fqn[len(legacy_pkg) :]
    # Fall back: keep simple name under target root package leaf
    simple = legacy_fqn.rsplit(".", 1)[-1]
    # Preserve relative package suffix after common root when possible
    parts = legacy_fqn.split(".")
    if len(parts) >= 2:
        # Preserve trailing layer segment (model/repository/service/…) under target.
        for i, p in enumerate(parts):
            if p in ("model", "repository", "service", "rest", "util", "mapper"):
                return target_pkg + "." + ".".join(parts[i:])
    return f"{target_pkg}.{simple}"


def _path_for_fqn(fqn: str) -> str:
    return "src/main/java/" + fqn.replace(".", "/") + ".java"


def condensation_order(analysis: dict) -> tuple[list[str], dict[int, str]]:
    """Unit keys or SCC ids — never flattened multi-member SCCs (ADR-24 §2.1)."""
    imports = analysis["imports"]
    fan_in = analysis["fan_in"]
    sccs = analysis["sccs"]
    fqn_scc: dict[str, int] = {}
    for i, comp in enumerate(sccs):
        for f in comp:
            fqn_scc[f] = i
    succ: dict[int, set[int]] = {i: set() for i in range(len(sccs))}
    pred_count = {i: 0 for i in range(len(sccs))}
    for fqn, deps in imports.items():
        a = fqn_scc.get(fqn)
        if a is None:
            continue
        for d in deps:
            b = fqn_scc.get(d)
            if b is None or b == a:
                continue
            if a not in succ[b]:
                succ[b].add(a)
                pred_count[a] += 1
    ready = sorted(
        (i for i in range(len(sccs)) if pred_count[i] == 0),
        key=lambda i: (-max((fan_in[f] for f in sccs[i]), default=0), min(sccs[i])),
    )
    order: list[str] = []
    seen: set[int] = set()
    scc_id_of: dict[int, str] = {}
    multi_n = 0
    for i, comp in enumerate(sccs):
        if len(comp) > 1:
            multi_n += 1
            scc_id_of[i] = f"SCC-{multi_n}"
    while ready:
        i = ready.pop(0)
        if i in seen:
            continue
        seen.add(i)
        if len(sccs[i]) == 1:
            order.append(sccs[i][0])
        else:
            order.append(scc_id_of[i])
        for a in sorted(succ.get(i, ()), key=lambda j: (min(sccs[j]), j)):
            pred_count[a] -= 1
            if pred_count[a] == 0:
                ready.append(a)
        ready.sort(
            key=lambda j: (
                -max((fan_in[f] for f in sccs[j]), default=0),
                min(sccs[j]),
            )
        )
    for i, comp in enumerate(sccs):
        if i not in seen:
            if len(comp) == 1:
                order.append(comp[0])
            else:
                order.append(scc_id_of[i])
    return order, scc_id_of


def build_model(
    root: Path,
    legacy_root: Path,
    *,
    preserve_stories: Optional[list[dict]] = None,
) -> dict[str, Any]:
    legacy_pkg, target_pkg = _read_packages(root)
    analysis = dependency_order.analyze(str(legacy_root))
    classes = analysis["classes"]
    imports = analysis["imports"]
    fan_in = analysis["fan_in"]
    cycles = analysis["cycles"]
    order, scc_id_of = condensation_order(analysis)

    fqn_to_scc: dict[str, str] = {}
    sccs_out: list[dict] = []
    for i, comp in enumerate(analysis["sccs"]):
        if len(comp) <= 1:
            continue
        sid = scc_id_of[i]
        members = sorted(comp)
        for m in members:
            fqn_to_scc[m] = sid
        # cycle edge labels (undirected pairs among members that import each other)
        cycle_edges: list[str] = []
        for a in members:
            for b in imports.get(a, ()):
                if b in fqn_to_scc and fqn_to_scc[b] == sid and a < b:
                    cycle_edges.append(f"{a.rsplit('.',1)[-1]}<->{b.rsplit('.',1)[-1]}")
        sccs_out.append({"id": sid, "members": members, "cycles": sorted(set(cycle_edges))})

    # O-ADR24FIND: Findings IR is the only findings identity input.
    import findings_ir

    ir = findings_ir.ensure_ir(root)

    units: list[dict] = []
    for fqn, rel in sorted(classes.items()):
        # dependency-order paths are relative to legacy root (often already src/...)
        legacy_path = rel if rel.startswith("src/") else f"src/main/java/{rel}"
        # normalize when analyze walked from legacy root containing src/
        if not legacy_path.startswith("src/") and "/src/" in rel:
            legacy_path = rel[rel.index("src/") :]
        target_fqn = _remap_fqn(fqn, legacy_pkg, target_pkg)
        target_path = _path_for_fqn(target_fqn)
        staging_path = f"migration/staging/{legacy_path}"
        alt = root / "migration" / "staging" / legacy_path
        if alt.is_file():
            staging_path = str(alt.relative_to(root))
        elif (root / staging_path).is_file():
            pass

        units.append(
            {
                "key": fqn,
                "kind": "java",
                "legacy_fqn": fqn,
                "legacy_path": legacy_path,
                "target_fqn": target_fqn,
                "target_path": target_path,
                "staging_path": staging_path,
                "scc": fqn_to_scc.get(fqn),
                "depends_on": sorted(imports.get(fqn, ())),
                "fan_in": int(fan_in.get(fqn, 0)),
                "fan_out": len(imports.get(fqn, ())),
                "findings": [],
            }
        )

    # Non-java structural seeds from common migration paths (ADR-24 §2.7)
    for rel, kind in (
        ("pom.xml", "pom"),
        ("src/main/resources/application.properties", "resources"),
        ("src/main/resources/application.yml", "resources"),
    ):
        lp = legacy_root / rel
        if lp.is_file():
            key = f"coord:{rel}"
            units.append(
                {
                    "key": key,
                    "kind": kind,
                    "legacy_fqn": None,
                    "legacy_path": rel,
                    "target_fqn": None,
                    "target_path": rel,
                    "staging_path": f"migration/staging/{rel}",
                    "scc": None,
                    "depends_on": [],
                    "fan_in": 0,
                    "fan_out": 0,
                    "findings": [],
                }
            )

    # Also seed resource units referenced by IR incidents (properties etc.)
    known_lp = {u.get("legacy_path") for u in units}
    for rule in ir.get("rules") or []:
        for inc in rule.get("incidents") or []:
            lp = (inc.get("legacy_path") or "").strip()
            if not lp or lp in known_lp:
                continue
            if lp.endswith(".java"):
                continue  # java must come from class graph
            kind = findings_ir.infer_kind(lp)
            key = f"coord:{lp}"
            units.append(
                {
                    "key": key,
                    "kind": kind,
                    "legacy_fqn": None,
                    "legacy_path": lp,
                    "target_fqn": None,
                    "target_path": lp,
                    "staging_path": f"migration/staging/{lp}",
                    "scc": None,
                    "depends_on": [],
                    "fan_in": 0,
                    "fan_out": 0,
                    "findings": [],
                }
            )
            known_lp.add(lp)

    findings, units, unbound = findings_ir.bind_findings_to_units(ir, units)
    bind_reds = findings_ir.lint_bind_closed(ir, findings)
    # ADR-25 / F-unbound-zero: pristine input ⇒ unbound must be empty (no waivers)
    bind_reds.extend(findings_ir.lint_unbound_zero(unbound))

    prov = ir.get("provenance") or {}
    model: dict[str, Any] = {
        "provenance": {
            "producer": "m1",
            "source_sha": _git_head(legacy_root if (legacy_root / ".git").exists() else root),
            "findings_sha256": prov.get("source_sha256") or "",
            "findings_ir_sha256": prov.get("ir_sha256") or "",
            "legacy_package": legacy_pkg,
            "target_package": target_pkg,
            "tool_versions": {"dependency_order": "adr24", "findings_ir": "v1"},
            "generated_at": _utc(),
            "findings_unbound": unbound[:50],
            "findings_bind_reds": bind_reds,
        },
        "units": units,
        "sccs": sccs_out,
        "order": order,
        "findings": findings,
        "stories": preserve_stories if preserve_stories is not None else [],
    }
    model["_cycles_count"] = len(cycles)
    model["_bind_reds"] = bind_reds
    return model


def load(root: Path) -> dict[str, Any]:
    path = root / MODEL_REL
    if not path.is_file():
        raise FileNotFoundError(f"missing {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def save(root: Path, model: dict[str, Any]) -> Path:
    path = root / MODEL_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    # strip private keys
    out = {k: v for k, v in model.items() if not k.startswith("_")}
    path.write_text(json.dumps(out, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    return path


def unit_by_key(model: dict, key: str) -> Optional[dict]:
    for u in model.get("units") or []:
        if u.get("key") == key:
            return u
    return None


def units_for_story(model: dict, sid: str) -> list[dict]:
    for st in model.get("stories") or []:
        if st.get("id") == sid:
            keys = set(st.get("units") or [])
            return [u for u in model.get("units") or [] if u.get("key") in keys]
    return []


def scc_of(model: dict, key: str) -> Optional[dict]:
    u = unit_by_key(model, key)
    if not u or not u.get("scc"):
        return None
    for s in model.get("sccs") or []:
        if s.get("id") == u["scc"]:
            return s
    return None


def order_for_story(model: dict, sid: str) -> list[str]:
    keys = {u["key"] for u in units_for_story(model, sid)}
    if not keys:
        return list(model.get("order") or [])
    scc_ids = {
        u["scc"]
        for u in units_for_story(model, sid)
        if u.get("scc")
    }
    out: list[str] = []
    for item in model.get("order") or []:
        if item in keys or item in scc_ids:
            out.append(item)
    return out


def context_for(model: dict, sid: str, *, root: Optional[Path] = None) -> str:
    """Structured M3 projection — no markdown scrape (ADR-24 G4) + ADR-38 snippets.

    O-M3SNIPPET / ADR-40: every resolvable decision cite= carries SNIPPET text
    (±2 lines) so the M3 seat must not fetch legacy files (same rule as
    context_for_m2). Generated/unresolvable cites are omitted.
    """
    units = units_for_story(model, sid)
    if not units and not (model.get("stories") or []):
        # Pre-assign_stories: project by matching nothing — caller may pass scope
        units = list(model.get("units") or [])
    # Snippet resolver (optional — fixtures without legacy still project structure)
    snip_fn = None
    is_gen = None
    lr = None
    if root is not None:
        try:
            sys.path.insert(0, str(_HARNESS))
            from profile_anchors import (  # type: ignore
                is_generated_build_path,
                resolve_legacy_root,
                snippet_at_path_line,
            )

            snip_fn = snippet_at_path_line
            is_gen = is_generated_build_path
            legacy_env = os.environ.get("LEGACY_ROOT", "").strip() or None
            lr = resolve_legacy_root(root, legacy_env)
        except Exception:
            snip_fn = None
    lines = [
        "===== BEGIN DERIVED FACTS (authoritative — migration model projection) =====",
        "O-M3DERIVEDCTX: where BRIEF and DERIVED FACTS disagree, DERIVED FACTS win.",
        "O-M3SNIPPET / ADR-38: copy quotes from SNIPPET only — do NOT read /projects/legacy.",
        f"story: {sid}",
        f"units ({len(units)}):",
    ]
    n_cite = 0
    n_snip = 0
    for u in units:
        if u.get("kind") != "java":
            lines.append(
                f"  - [{u.get('kind')}] {u.get('target_path')} <- {u.get('legacy_path')}"
            )
            continue
        scc = u.get("scc") or "-"
        fids = ",".join(u.get("findings") or []) or "-"
        d = u.get("decision") if isinstance(u.get("decision"), dict) else {}
        role = (d.get("role") if d else None) or "UNDECIDED"
        cite = ""
        snip: Optional[str] = None
        if snip_fn and isinstance(d, dict):
            ev = d.get("evidence") if isinstance(d.get("evidence"), dict) else None
            if ev and ev.get("path"):
                ep = str(ev.get("path") or "").replace("\\", "/")
                if not (is_gen and is_gen(ep)):
                    snip = snip_fn(
                        root,
                        ep,
                        ev.get("line") or 0,
                        legacy_root=lr,
                        before=2,
                        after=2,
                    )
                    if snip:
                        cite = f" cite={ep}:{ev.get('line')}:{ev.get('token')}"
                        n_cite += 1
                        n_snip += 1
        lines.append(
            f"  - {u.get('target_fqn')} <- {u.get('legacy_fqn')}  role={role} "
            f"scc={scc}  findings=[{fids}]{cite}"
        )
        if snip:
            lines.append("    SNIPPET:")
            for sl in snip.splitlines():
                lines.append(f"    | {sl}")
    # convert-together batches intersecting this story
    unit_keys = {u["key"] for u in units}
    for scc in model.get("sccs") or []:
        members = set(scc.get("members") or [])
        if not members & unit_keys:
            continue
        simples = [m.rsplit(".", 1)[-1] for m in scc.get("members") or []]
        cycles = ", ".join(scc.get("cycles") or []) or "cyclic"
        lines.append(
            f"convert-together: {scc['id']} = {{{', '.join(simples)}}}  ({cycles}) — ONE task"
        )
    ord_items = order_for_story(model, sid)
    if ord_items:
        pretty = []
        for i, item in enumerate(ord_items, 1):
            if item.startswith("SCC-"):
                scc = next((s for s in model.get("sccs") or [] if s["id"] == item), None)
                if scc:
                    names = ",".join(m.rsplit(".", 1)[-1] for m in scc["members"])
                    pretty.append(f"{i} {item}{{{names}}}")
                else:
                    pretty.append(f"{i} {item}")
            else:
                pretty.append(f"{i} {item.rsplit('.', 1)[-1]}")
        lines.append("order: " + " · ".join(pretty))
    # Typed tasks already bound for this story (ADR-35 / ADR-40)
    typed = [t for t in (model.get("tasks") or []) if t.get("sid") == sid]
    if typed:
        lines.append(f"typed_tasks ({len(typed)}): harness-generated IDs — seat fills JUDGMENT only")
        for t in typed:
            lines.append(
                f"  - {t.get('id')} owns={','.join(t.get('unit_keys') or [])} "
                f"filled={bool(t.get('filled'))} acceptance_derived=yes"
            )
    lines.append(f"provenance: m3snip_cites={n_cite} m3snip_snippets={n_snip}")
    lines.append("===== END DERIVED FACTS =====")
    return "\n".join(lines)


def context_for_scope(
    model: dict, scope_paths: list[str], *, root: Optional[Path] = None
) -> str:
    """Projection before stories[] is bound — select units by exact legacy_path ∈ scope.

    O-ADR24BASENAME: no Path(...).name / suffix joins — scope must list full paths
    (or exact prefixes only when the scope entry itself is a directory path ending /).
    """
    scope = {p.strip().rstrip("/") for p in scope_paths if p.strip()}
    selected = []
    for u in model.get("units") or []:
        lp = (u.get("legacy_path") or "").strip()
        if not lp:
            continue
        if lp in scope:
            selected.append(u)
            continue
        # directory scopes: exact prefix with path boundary (not basename)
        for sp in scope:
            if sp.endswith(".java") or "." in Path(sp).name:
                continue
            if lp.startswith(sp.rstrip("/") + "/"):
                selected.append(u)
                break
    # Build a temporary story view
    tmp = dict(model)
    tmp["stories"] = [
        {
            "id": "SCOPE",
            "units": [u["key"] for u in selected],
            "findings": [],
            "deploy": False,
        }
    ]
    return context_for(tmp, "SCOPE", root=root).replace(
        "story: SCOPE", "story: (scope projection)"
    )


def profile_units(model: dict) -> list[dict]:
    """ADR-26 — architecture-bearing java units for M1 PROFILE coverage.

    Single SoT for the PROFILE class universe (same model as M2/M3).
    Excludes package-info.java — no architectural role to harvest/redesign.
    Identity is legacy_fqn / legacy_path (never bare basename alone).
    """
    out: list[dict] = []
    for u in model.get("units") or []:
        if u.get("kind") != "java":
            continue
        lp = (u.get("legacy_path") or "").replace("\\", "/")
        fqn = u.get("legacy_fqn") or ""
        if lp.endswith("package-info.java") or fqn.endswith("package-info"):
            continue
        out.append(u)
    return out


def context_for_profile(
    model: dict,
    *,
    root: Optional[Path] = None,
    undecided_only: bool = False,
    limit: int = 0,
    legacy: Optional[str] = None,
) -> str:
    """ADR-26 + ADR-31 — M1 PROFILE projection: checklist, not recall.

    Same DERIVED FACTS pattern as context_for (M3). PROFILE must classify
    every listed unit; rubric grades against the full universe.

    O-PROF1OF79STOP: `--undecided-only --limit N` projects a **batch** of
    units still needing a credited typed decision (null or evidence_miss),
    so seats are not asked to author 79 anchors in one overloaded prompt.

    ADR-31: each unit carries a **pre-verified anchor set**. The seat
    SELECTs evidence from that set — it does not search for line numbers.
    Apply refuses evidence ∉ the set (F-anchor-membership).
    """
    units = profile_units(model)
    batch_note = ""
    if undecided_only and root is not None:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from profile_roles import evaluate_roles  # type: ignore

        ev = evaluate_roles(Path(root), legacy=legacy)
        need = set(ev.get("undecided") or [])
        units = [
            u
            for u in units
            if (u.get("legacy_fqn") or u.get("key") or "?") in need
        ]
        batch_note = " (undecided-only batch — fill these before the rest)"
    if limit and limit > 0:
        units = units[:limit]
        batch_note = (batch_note or "") + f" (limit={limit})"
    # ADR-31 — precompute anchors once for the projected batch.
    anchor_map: dict = {}
    if root is not None:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from profile_anchors import project_text_for_units  # type: ignore

        anchor_map = project_text_for_units(Path(root), units, legacy=legacy)
    lines = [
        "===== BEGIN DERIVED FACTS (authoritative — PROFILE model projection) =====",
        "EVERY unit below needs a typed decision in",
        "migration/profile-decisions.json (or model.units[].decision):",
        "role=HARVEST|REDESIGN, rationale, evidence={path,line,token}.",
        "Evidence MUST be SELECTED from the unit's projected anchors",
        "(pre-verified path:line:token). Do NOT invent line numbers. Apply",
        "refuses evidence outside the projected set (F-anchor-membership).",
        "§7 markdown is RENDERED from those decisions — do not author role bullets.",
        "Where ANALYSIS prose and DERIVED FACTS disagree, DERIVED FACTS win.",
        "O-ADR27: source *Mapper.java interfaces ARE classify (in this list).",
        "Never class-role *MapperImpl or target/generated-sources — build-owned.",
        # Wording avoids the literal "package-info" so instruments that assert
        # the unit is absent from the projection body do not false-fail.
        f"profile-units ({len(units)} java, pkg-info rows omitted){batch_note}:",
    ]
    for u in units:
        fqn = u.get("legacy_fqn") or u.get("key") or "?"
        lp = u.get("legacy_path") or "?"
        scc = u.get("scc") or "-"
        fids = ",".join(u.get("findings") or []) or "-"
        simple = fqn.rsplit(".", 1)[-1]
        hint = "classify"
        if simple.endswith("Mapper") and "mapper" in lp.lower():
            hint = "classify-source-mapper"
        d = u.get("decision") if isinstance(u.get("decision"), dict) else None
        dstat = (
            f"decision={d.get('role')}"
            if d and d.get("role") in ("HARVEST", "REDESIGN")
            else "decision=null"
        )
        lines.append(
            f"  - {fqn}  path={lp}  simple={simple}  scc={scc}  "
            f"findings=[{fids}]  hint={hint}  {dstat}"
        )
        if root is not None:
            from profile_anchors import format_anchors_block  # type: ignore

            lines.extend(format_anchors_block(anchor_map.get(fqn) or []))
    # non-java demand still visible for modernization surface
    other = [
        u
        for u in model.get("units") or []
        if u.get("kind") != "java" and (u.get("findings") or [])
    ]
    if other:
        lines.append(f"non-java demand units ({len(other)}) — cite in §5, not §7 class-roles:")
        for u in other:
            fids = ",".join(u.get("findings") or []) or "-"
            lines.append(
                f"  - [{u.get('kind')}] {u.get('legacy_path')}  findings=[{fids}]"
            )
    lines.append("===== END DERIVED FACTS =====")
    return "\n".join(lines)


def emit_profile_skeleton(root: Path) -> int:
    """ADR-29 — PROFILE pre-seat projection (typed decisions, not prose roles).

    Opens model.units[].decision = null and migration/profile-decisions.json.
    §7 is a rendered view — do **not** author role bullets in markdown; fill
    profile-decisions.json (role + rationale + evidence.path/line/token).
    Closes W5-023 scaffold false-green and the §7 harvest round-trip.
    """
    from profile_close import _sec7_span  # type: ignore
    from profile_roles import init_roles, render_sec7  # type: ignore

    profile = root / "migration" / "architecture-profile.md"
    if not profile.is_file():
        profile.parent.mkdir(parents=True, exist_ok=True)
        profile.write_text(
            "# Architecture profile\n\n"
            "## 1. Purpose & Domain\n\n"
            "(LLM fills — evidence or silence.)\n\n"
            "## 2. Components & Relationships\n\n"
            "(LLM fills — cite dependency-order.md.)\n\n"
            "## 3. Integration Surfaces\n\n"
            "(LLM fills.)\n\n"
            "## 4. Behavioral Contract Sources\n\n"
            "(LLM fills.)\n\n"
            "## 5. Modernization Surface\n\n"
            "(LLM fills — findings-inventory.)\n\n"
            "## 6. Domain Boundaries\n\n"
            "(LLM fills.)\n\n"
            "## 7. Class Roles & Target Contract\n\n"
            "<!-- rendered from model.units[].decision after PROFILE close -->\n\n",
            encoding="utf-8",
        )
    else:
        text = profile.read_text(encoding="utf-8")
        start, _end = _sec7_span(text)
        if start < 0:
            profile.write_text(
                text.rstrip()
                + "\n\n## 7. Class Roles & Target Contract\n\n"
                + "<!-- rendered from model.units[].decision after PROFILE close -->\n\n",
                encoding="utf-8",
            )
    rc = init_roles(root)
    render_sec7(root, profile=str(profile))
    n_units = len(profile_units(load(root)))
    print(
        f"O-ADR29 skeleton: model.units[].decision checklist ({n_units} units); "
        f"fill migration/profile-decisions.json — §7 (Class Roles & Target Contract) "
        f"is rendered → {profile}"
    )
    return rc


def _decision_complete_local(d: Optional[dict]) -> bool:
    if not isinstance(d, dict):
        return False
    role = str(d.get("role") or "").upper()
    if role not in ("HARVEST", "REDESIGN"):
        return False
    ev = d.get("evidence") if isinstance(d.get("evidence"), dict) else None
    if not ev:
        return False
    return bool(ev.get("path") and ev.get("line") is not None and ev.get("token"))


def model_has_typed_decisions(model: dict) -> bool:
    """ADR-34: typed profile decisions present → stories[] from model, not roadmap."""
    for u in profile_units(model):
        d = u.get("decision") if isinstance(u.get("decision"), dict) else None
        if _decision_complete_local(d):
            return True
    return False


def _layer_for_legacy_path(path: str) -> str:
    """Packaging label only (not membership SoT) — mirrors m2-compose.layer_for_path."""
    p = (path or "").replace("\\", "/").lower()
    if p.endswith("pom.xml") or "/pom.xml" in p or p.endswith(".xml") and "src/" not in p:
        return "platform"
    if "/model/" in p or "/domain/" in p:
        return "model"
    if "/repository/" in p or "/repo/" in p or "/dao/" in p:
        return "repository"
    if "/service/" in p:
        return "service"
    if "/rest/" in p or "/web/" in p or "/controller/" in p or "/security/" in p:
        return "surface"
    if "/config/" in p or "/configuration/" in p:
        return "surface"
    return "other"


_LAYER_ORDER = (
    "platform",
    "model",
    "repository",
    "service",
    "surface",
    "other",
)
_LAYER_SLUG = {
    "platform": "platform-bom",
    "model": "domain-model",
    "repository": "repository-layer",
    "service": "service-layer",
    "surface": "rest-surface",
    "other": "remaining",
}


def assign_stories_from_model(root: Path, model: Optional[dict] = None) -> dict:
    """ADR-34 REV-2 / F-story-rendered — persist stories[] from typed partition.

    Membership = model.order + SCC-atomic + decision.role packaging layers.
    **Never reads roadmap.md** (roadmap is a rendered view only).
    """
    model = model or load(root)
    units = {
        u["key"]: u
        for u in profile_units(model)
        if u.get("key") and u.get("kind") == "java"
    }
    scc_members: dict[str, list[str]] = {}
    for scc in model.get("sccs") or []:
        sid = scc.get("id") or ""
        mem = [m for m in (scc.get("members") or []) if m in units]
        if sid and mem:
            scc_members[sid] = mem

    def _unit_layer(key: str) -> str:
        u = units.get(key) or {}
        return _layer_for_legacy_path(u.get("legacy_path") or "")

    def _scc_layer(members: list[str]) -> str:
        layers = [_unit_layer(m) for m in members]
        if not layers:
            return "other"
        return sorted(layers, key=lambda lay: _LAYER_ORDER.index(lay))[0]

    unit_to_layer: dict[str, str] = {}
    for item in model.get("order") or []:
        if item in scc_members:
            lay = _scc_layer(scc_members[item])
            for m in scc_members[item]:
                unit_to_layer[m] = lay
        elif item in units:
            unit_to_layer[item] = _unit_layer(item)
    for key in units:
        unit_to_layer.setdefault(key, _unit_layer(key))

    # F-scc-atomic: every SCC member shares one layer/story.
    for sid, mem in scc_members.items():
        lays = {unit_to_layer.get(m) for m in mem}
        if len(lays) > 1:
            raise SystemExit(
                f"O-ADR34 assign_stories RED: {sid} split across layers {sorted(lays)} "
                f"(F-scc-atomic)"
            )

    layer_units: dict[str, list[str]] = {lay: [] for lay in _LAYER_ORDER}
    for key, lay in unit_to_layer.items():
        layer_units.setdefault(lay, []).append(key)

    stories: list[dict] = []
    claimed: dict[str, str] = {}
    idx = 1
    for lay in _LAYER_ORDER:
        keys = layer_units.get(lay) or []
        if not keys:
            continue
        sid = f"S{idx:02d}"
        for k in keys:
            if k in claimed and claimed[k] != sid:
                raise SystemExit(
                    f"O-ADR34 assign_stories RED: unit {k} dual-owned by "
                    f"{claimed[k]} and {sid}"
                )
            claimed[k] = sid
        fids: list[str] = []
        for k in keys:
            fids.extend(units.get(k, {}).get("findings") or [])
        stories.append(
            {
                "id": sid,
                "slug": _LAYER_SLUG.get(lay, lay),
                "units": list(keys),
                "findings": sorted(set(fids)),
                # F-deploy-derived: only last story is deployable by default.
                "deploy": False,
                "layer": lay,
            }
        )
        idx += 1

    if stories:
        for st in stories[:-1]:
            st["deploy"] = False
        stories[-1]["deploy"] = True

    all_java = set(units)
    orphans = sorted(all_java - set(claimed))
    if orphans:
        raise SystemExit(
            f"O-ADR34 assign_stories RED: {len(orphans)} unassigned java unit(s) "
            f"(F-story-partition): {orphans[:8]}"
        )

    model["stories"] = stories
    prov = model.setdefault("provenance", {})
    prov["stories_assigned_at"] = _utc()
    prov["stories_source"] = "model-partition"  # F-story-rendered witness
    save(root, model)
    print(
        f"O-ADR34: assign_stories_from_model stories={len(stories)} "
        f"units={len(claimed)} source=model-partition (F-story-rendered)"
    )
    return model


def assign_stories_from_roadmap(root: Path, model: Optional[dict] = None) -> dict:
    """Legacy / fixture path — parse roadmap.md when typed decisions are absent."""
    model = model or load(root)
    roadmap = root / "migration" / "roadmap.md"
    if not roadmap.is_file():
        raise FileNotFoundError("migration/roadmap.md required for assign_stories")
    text = roadmap.read_text(encoding="utf-8", errors="replace")
    blocks = re.split(r"(?m)^##\s+(S\d+)\b", text)
    # blocks: [pre, S01, body1, S02, body2, ...]
    stories: list[dict] = []
    claimed: dict[str, str] = {}
    units_by_legacy_path = {
        u.get("legacy_path"): u for u in model.get("units") or [] if u.get("legacy_path")
    }
    units_by_key = {u["key"]: u for u in model.get("units") or []}

    for i in range(1, len(blocks), 2):
        sid = blocks[i]
        body = blocks[i + 1] if i + 1 < len(blocks) else ""
        sm = re.search(r"(?im)^-\s*slug:\s*(\S+)", body)
        slug = sm.group(1) if sm else sid
        dm = re.search(r"(?im)^-\s*deploy:\s*(true|false)", body)
        deploy = bool(dm and dm.group(1).lower() == "true")
        scm = re.search(r"(?im)^-\s*scope:\s*(.+)$", body)
        scope_raw = scm.group(1).strip() if scm else ""
        paths = [p.strip() for p in re.split(r"[\s,]+", scope_raw) if p.strip()]
        unit_keys: list[str] = []
        for p in paths:
            # O-ADR24BASENAME: exact legacy_path / coord key only — no basename join.
            u = units_by_legacy_path.get(p)
            if u is None:
                key = f"coord:{p}"
                if key in units_by_key:
                    u = units_by_key[key]
            if u is None:
                continue
            k = u["key"]
            if k in claimed and claimed[k] != sid:
                raise SystemExit(
                    f"O-ADR24 assign_stories RED: unit {k} dual-owned by "
                    f"{claimed[k]} and {sid}"
                )
            claimed[k] = sid
            if k not in unit_keys:
                unit_keys.append(k)

        # SCC-indivisible at M2: claiming any member claims the whole SCC into
        # this story; refuse only when members are already claimed elsewhere (F7).
        for scc in model.get("sccs") or []:
            members = scc.get("members") or []
            hit = [m for m in members if m in unit_keys]
            if not hit:
                continue
            for m in members:
                if m in claimed and claimed[m] != sid:
                    raise SystemExit(
                        f"O-ADR24 assign_stories RED: {scc['id']} spans "
                        f"{claimed[m]} and {sid} (F7)"
                    )
                claimed[m] = sid
                if m not in unit_keys:
                    unit_keys.append(m)

        fids: list[str] = []
        for k in unit_keys:
            fids.extend(units_by_key.get(k, {}).get("findings") or [])
        stories.append(
            {
                "id": sid,
                "slug": slug,
                "units": unit_keys,
                "findings": sorted(set(fids)),
                "deploy": deploy,
            }
        )

    # Total + disjoint: every java unit assigned exactly once.
    all_java = {
        u["key"] for u in model.get("units") or [] if u.get("kind") == "java"
    }
    orphans = sorted(all_java - set(claimed))
    if orphans:
        raise SystemExit(
            f"O-ADR24 assign_stories RED: {len(orphans)} unassigned java unit(s) "
            f"(total invariant): {orphans[:8]}"
        )

    model["stories"] = stories
    prov = model.setdefault("provenance", {})
    prov["stories_assigned_at"] = _utc()
    prov["stories_source"] = "roadmap-parse"
    save(root, model)
    return model


def assign_stories(root: Path, model: Optional[dict] = None) -> dict:
    """M2 sole mutation: fill stories[] — ADR-34 prefers typed model partition.

    When typed decisions exist: **F-story-rendered** — never parse roadmap.md.
    Fixture / pre-decision path may still parse roadmap.
    """
    model = model or load(root)
    if model_has_typed_decisions(model):
        return assign_stories_from_model(root, model)
    return assign_stories_from_roadmap(root, model)


def context_for_m2(root: Path, model: Optional[dict] = None) -> str:
    """ADR-34 / ADR-37 / ADR-38 — projected M2 facts with anchored snippets.

    Seat fills JUDGMENT (titles, rationale, quotes). Every ``cite=`` carries
    the source text (±N lines) so the seat must not fetch legacy files
    (F-no-discovery). Unresolvable/generated cites are omitted entirely —
    never projected as a pointer that licenses a tree read.
    """
    sys.path.insert(0, str(_HARNESS))
    from profile_anchors import (  # type: ignore
        is_generated_build_path,
        resolve_legacy_root,
        snippet_at_path_line,
    )

    model = model or load(root)
    if not (model.get("stories") or []):
        model = assign_stories(root, model)
    units_by_key = {u["key"]: u for u in model.get("units") or [] if u.get("key")}
    legacy_env = os.environ.get("LEGACY_ROOT", "").strip() or None
    lr = resolve_legacy_root(root, legacy_env)
    lines = [
        "O-ADR34 M2 PROJECTED FACTS (complete for this seat — do not rediscover)",
        "O-ADR38: every cite= includes SNIPPET text — copy quotes from SNIPPET only",
        f"stories_source={((model.get('provenance') or {}).get('stories_source') or '?')}",
        "",
    ]
    n_cite = 0
    n_snip = 0
    for st in model.get("stories") or []:
        sid = st.get("id") or "?"
        lines.append(
            f"## {sid} slug={st.get('slug') or sid} deploy={bool(st.get('deploy'))} "
            f"layer={st.get('layer') or '?'}"
        )
        lines.append(f"units ({len(st.get('units') or [])}):")
        for k in st.get("units") or []:
            u = units_by_key.get(k) or {}
            d = u.get("decision") if isinstance(u.get("decision"), dict) else {}
            role = (d.get("role") if d else None) or "UNDECIDED"
            lp = u.get("legacy_path") or ""
            tc = d.get("target_contract") if d else None
            tc_s = ""
            if isinstance(tc, dict) and tc:
                tc_s = " tc=" + ",".join(
                    f"{kk}" for kk, vv in sorted(tc.items()) if vv and kk != "decisive"
                )
            elif isinstance(tc, str) and tc.strip():
                tc_s = f" tc={tc.strip()[:80]}"
            ev = d.get("evidence") if isinstance(d, dict) else None
            cite = ""
            snip: Optional[str] = None
            if isinstance(ev, dict) and ev.get("path"):
                ep = str(ev.get("path") or "").replace("\\", "/")
                if is_generated_build_path(ep):
                    # Refuse — do not emit a pointer the seat would chase.
                    pass
                else:
                    snip = snippet_at_path_line(
                        root,
                        ep,
                        ev.get("line") or 0,
                        legacy_root=lr,
                        before=2,
                        after=2,
                    )
                    if snip:
                        cite = (
                            f" cite={ep}:{ev.get('line')}:{ev.get('token')}"
                        )
                        n_cite += 1
                        n_snip += 1
                    # else: unresolvable — omit cite (M1/SoT gap, not a read license)
            lines.append(f"  - {k} role={role} path={lp}{tc_s}{cite}")
            if snip:
                lines.append("    SNIPPET:")
                for sl in snip.splitlines():
                    lines.append(f"    | {sl}")
        fids = st.get("findings") or []
        if fids:
            lines.append("findings: " + ", ".join(fids[:20]))
        lines.append("")
    lines.append(
        f"provenance: adr38_cites={n_cite} adr38_snippets={n_snip}"
    )
    lines.append(
        "Rules: do NOT change unit membership/scope/deploy (harness SoT). "
        "Fill JUDGMENT titles/rationale/quotes by copying SNIPPET lines above "
        "(cite= is an id only). "
        "Do NOT bash/read/glob /projects/legacy — facts+code text are in this packet "
        "(F-no-discovery / ADR-38)."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ADR-35 / ADR-40 — typed model.tasks[] (harness SoT; tasks.md is a VIEW)
# ---------------------------------------------------------------------------


def _unit_slug(key: str) -> str:
    simple = (key or "unit").rsplit(".", 1)[-1]
    slug = re.sub(r"[^A-Za-z0-9]+", "", simple)
    return (slug or "unit")[:48]


def derive_acceptance(unit: dict) -> list[str]:
    """Acceptance is a function of role + target_contract — never seat prose (ADR-35)."""
    d = unit.get("decision") if isinstance(unit.get("decision"), dict) else {}
    role = str((d or {}).get("role") or "").upper()
    if role == "HARVEST":
        return [
            "byte-fidelity vs migration/staging (LOC + serialVersionUID)",
            "package rename only; no behavior change",
        ]
    if role == "REDESIGN":
        out = ["implements typed target_contract for this unit"]
        tc = (d or {}).get("target_contract")
        # Affirmative no-flags (O-TCABSENT): M1 may set target_contract={} or
        # {"decisive": true/false} with no other truthy flags — distinct from
        # tc key absent (genuine M1 omission → refuse ship / complete at M1).
        if isinstance(tc, dict):
            flags = [
                f"contract:{k}"
                for k, v in sorted(tc.items())
                if v and k != "decisive"
            ]
            if flags:
                out.extend(flags)
            else:
                out.append("REDESIGN no-flags-apply (M1 affirmative)")
        elif isinstance(tc, str) and tc.strip():
            out.append(tc.strip()[:120])
        else:
            # tc missing / null — not the same as empty dict
            out.append("REDESIGN without target_contract — complete at M1")
        return out
    return ["role undecided — refuse ship until M1 decision exists"]


def _mechanical_class_shape(root: Path, owns: str, *, role: str = "") -> tuple[str, str]:
    # HARVEST is package-rename of an existing type — never "create" (W4-553).
    if str(role or "").upper() == "HARVEST":
        return "rewrite", "modify"
    if not owns.endswith(".java"):
        return "rewrite", "modify"
    try:
        exists = (root / owns.lstrip("./")).is_file()
    except OSError:
        exists = False
    if exists:
        return "rewrite", "modify"
    return "infer", "create"


def _load_god_nodes(root: Path) -> set[str]:
    """FQNs marked god-node in dependency-order.md (S-GODORDER / O-GODORDEREMIT)."""
    dep = root / "migration" / "dependency-order.md"
    gods: set[str] = set()
    if not dep.is_file():
        return gods
    for line in dep.read_text(encoding="utf-8", errors="replace").splitlines():
        dm = re.match(r"^\s*(\d+)\.\s+([\w.]+)\s+\(", line)
        if dm and re.search(r"(?i)god-node", line):
            gods.add(dm.group(2))
    return gods


def _ensure_god_characterization_tasks(
    root: Path, model: dict, tasks: list[dict]
) -> list[dict]:
    """Emit characterization tasks before god-node convert (W4-566 / O-GODORDEREMIT).

    Same class as O-TASKCLASSORDER: assign_tasks owns the ordering fact that
    plan-lint S-GODORDER checks. HARVEST convert is exempt (O-GODORDERCVT).
    """
    gods = _load_god_nodes(root)
    if not gods:
        return tasks
    god_simple = {g.rsplit(".", 1)[-1]: g for g in gods}
    out = list(tasks)
    # Index existing char coverage by simple name
    char_covered: set[str] = set()
    for t in out:
        blob = f"{t.get('goal') or ''} {t.get('title') or ''} {' '.join(t.get('owns') or [])}"
        if t.get("kind") == "characterize" or re.search(
            r"(?i)\bcharacterization\b", blob
        ):
            for simple in god_simple:
                if re.search(rf"\b{re.escape(simple)}\b", blob):
                    char_covered.add(simple)
    # Per story: for each REDESIGN convert owning a god-node, ensure char.
    by_sid: dict[str, list[dict]] = {}
    for t in out:
        by_sid.setdefault(str(t.get("sid") or ""), []).append(t)
    emitted: list[dict] = []
    for sid, story in by_sid.items():
        if not sid:
            continue
        # target package for test path
        try:
            cfg = yaml_legacy_target(root)  # may not exist — fallback
        except Exception:
            cfg = ("", "com.demo")
        target_pkg = cfg[1] if isinstance(cfg, tuple) else "com.demo"
        for t in story:
            if str(t.get("role") or "").upper() == "HARVEST":
                continue
            if str(t.get("port") or "").lower() != "reimplement" and not re.search(
                r"(?i)\bconvert\b|\breimplement\b",
                f"{t.get('goal') or ''} {t.get('plan') or ''}",
            ):
                continue
            for key in t.get("unit_keys") or []:
                simple = str(key).rsplit(".", 1)[-1]
                if simple not in god_simple or simple in char_covered:
                    continue
                # Derive test owns from unit target_path when possible
                primary = unit_by_key(model, key)
                main_owns = ""
                if primary and primary.get("target_path"):
                    main_owns = str(primary.get("target_path"))
                elif t.get("owns"):
                    main_owns = str(t.get("owns")[0])
                if main_owns.startswith("src/main/java/") and main_owns.endswith(
                    ".java"
                ):
                    test_owns = "src/test/java/" + main_owns[len("src/main/java/") : -5] + "Test.java"
                else:
                    test_owns = (
                        f"src/test/java/{target_pkg.replace('.', '/')}/{simple}Test.java"
                    )
                char_id = f"{sid}-TC-{simple}Char"
                # Avoid dup ids
                if any(x.get("id") == char_id for x in out + emitted):
                    char_covered.add(simple)
                    continue
                emitted.append(
                    {
                        "id": char_id,
                        "sid": sid,
                        "seq": 0,
                        "unit_keys": [key],
                        "kind": "characterize",
                        "scc_id": None,
                        "owns": [test_owns],
                        "title": f"Characterize {simple} (god-node)",
                        "class": "infer",
                        "shape": "create",
                        "role": "REDESIGN",
                        "acceptance": [
                            f"{simple}Test pins legacy contract before convert "
                            f"(O-GODORDEREMIT / S-GODORDER)"
                        ],
                        "oracle": "absent",
                        "port": None,
                        "findings": [],
                        "goal": (
                            f"Add characterization tests for god-node {simple} "
                            f"before convert (O-GODORDEREMIT)."
                        ),
                        "plan": (
                            f"Write {test_owns} pinning public behaviour named "
                            f"in dependency-order / brief SNIPPET; no main-src edits."
                        ),
                        "risk": "low",
                        "filled": True,
                    }
                )
                char_covered.add(simple)
    return out + emitted


def yaml_legacy_target(root: Path) -> tuple[str, str]:
    """Return (legacyPackage, targetPackage) from migration.yaml — best effort."""
    p = root / "migration.yaml"
    leg, tgt = "", "com.demo"
    if not p.is_file():
        return leg, tgt
    for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^\s*legacyPackage:\s*(\S+)", line)
        if m:
            leg = m.group(1).strip()
        m = re.match(r"^\s*targetPackage:\s*(\S+)", line)
        if m:
            tgt = m.group(1).strip()
    return leg, tgt


def assign_tasks(root: Path, model: Optional[dict] = None) -> dict:
    """Generate model.tasks[] from condensation units — IDs harness-owned (ADR-35).

    Preserves seat JUDGMENT fields (goal/plan/risk/filled) when unit_keys match
    an existing task. Acceptance is always re-derived.
    """
    model = model or load(root)
    prev_by_keys: dict[tuple[str, ...], dict] = {}
    for t in model.get("tasks") or []:
        keys = tuple(sorted(t.get("unit_keys") or []))
        if keys:
            prev_by_keys[keys] = t
    tasks: list[dict] = []
    for st in model.get("stories") or []:
        sid = st.get("id") or ""
        if not sid:
            continue
        condensations = skeleton_condensation_units(model, sid)
        for i, cu in enumerate(condensations, start=1):
            members = list(cu.get("members") or [])
            keys_t = tuple(sorted(members))
            prev = prev_by_keys.get(keys_t) or {}
            slug = _unit_slug(cu.get("id") or (members[0] if members else f"t{i}"))
            tid = f"{sid}-T-{i:03d}-{slug}"
            owns = list(cu.get("owns") or [])
            primary = unit_by_key(model, members[0]) if members else None
            role = "UNDECIDED"
            acceptance: list[str] = ["role undecided — refuse ship until M1 decision exists"]
            if primary:
                d = primary.get("decision") if isinstance(primary.get("decision"), dict) else {}
                role = str((d or {}).get("role") or "UNDECIDED").upper()
                acceptance = derive_acceptance(primary)
            # SCC convert-together: shape=batch:SCC-N carries batch semantics
            # (W4-561 — one vocabulary; plan-lint typed mode must accept it).
            # HARVEST SCCs are class=rewrite so rewrite/infer order holds;
            # scc_id + unit_keys remain the atomicity SoT (O-HARVESTSHAPE).
            if cu.get("kind") == "scc":
                shape = f"batch:{cu.get('id')}"
                cls = "rewrite" if str(role).upper() == "HARVEST" else "infer"
                oracle = "absent"
                port = None
            else:
                one = owns[0] if owns else ""
                cls, shape = (
                    _mechanical_class_shape(root, one, role=role)
                    if one
                    else ("rewrite", "modify")
                )
                if str(role).upper() == "HARVEST":
                    cls, shape = "rewrite", "modify"
                oracle = "absent"
                port = None
                # W4-566: Port=reimplement is REDESIGN API-swap only — never
                # on HARVEST (that made S-GODORDER treat harvest as convert).
                if str(role).upper() != "HARVEST" and one and re.search(
                    r"(?i)\b(repository|spring\s*data|panache|jdbc)\b", one
                ):
                    port = "reimplement"
            task = {
                "id": tid,
                "sid": sid,
                "seq": i,
                "unit_keys": members,
                "kind": cu.get("kind") or "singleton",
                "scc_id": cu.get("id") if cu.get("kind") == "scc" else None,
                "owns": owns,
                "title": cu.get("title") or f"{slug} — skeleton",
                "class": cls,
                "shape": shape,
                "role": role,
                "acceptance": acceptance,
                "oracle": oracle,
                "port": port,
                "findings": list(st.get("findings") or []) if i == 1 else [],
                # JUDGMENT — seat-filled via write inversion (never author id/acceptance)
                "goal": prev.get("goal") or "",
                "plan": prev.get("plan") or "",
                "risk": prev.get("risk") or "",
                "filled": bool(prev.get("filled")),
            }
            tasks.append(task)
    # O-GODORDEREMIT (W4-566): characterization task before god-node convert.
    tasks = _ensure_god_characterization_tasks(root, model, tasks)
    # O-TASKCLASSORDER (W4-562): one owner for rewrite-before-infer.
    # assign_tasks emits satisfying order; plan-lint checks the same rule.
    # Stable partition per story — preserve relative condensation order
    # within each class; then renumber seq (ids stay stable for judgments).
    # Within infer: characterization before convert (O-GODORDEREMIT).
    ordered: list[dict] = []
    for st in model.get("stories") or []:
        sid = st.get("id") or ""
        if not sid:
            continue
        story = [t for t in tasks if t.get("sid") == sid]
        rewrites = [
            t for t in story if str(t.get("class") or "").lower() == "rewrite"
        ]
        rest = [
            t for t in story if str(t.get("class") or "").lower() != "rewrite"
        ]
        chars = [
            t
            for t in rest
            if t.get("kind") == "characterize"
            or re.search(r"(?i)\bcharacterization\b", str(t.get("goal") or ""))
        ]
        converts = [t for t in rest if t not in chars]
        for i, t in enumerate(rewrites + chars + converts, start=1):
            t["seq"] = i
            ordered.append(t)
    # Any tasks without a story id (should not happen) keep prior order.
    orphan = [t for t in tasks if t not in ordered]
    model["tasks"] = ordered + orphan
    prov = model.setdefault("provenance", {})
    prov["tasks_source"] = "model-condensation"
    prov["tasks_assigned_at"] = _utc()
    save(root, model)
    return model


def tasks_for_story(model: dict, sid: str) -> list[dict]:
    return [t for t in (model.get("tasks") or []) if t.get("sid") == sid]


def brief_slug_for_story(root: Path, sid: str, model: Optional[dict] = None) -> str:
    briefs = sorted((root / "migration" / "briefs").glob(f"{sid}-*.md"))
    if briefs:
        return briefs[0].stem
    model = model or load(root)
    for st in model.get("stories") or []:
        if st.get("id") == sid:
            slug = st.get("slug") or sid
            return f"{sid}-{slug}" if not str(slug).startswith(sid) else str(slug)
    return sid


def render_tasks_md(root: Path, sid: str, model: Optional[dict] = None) -> Path:
    """Render specs/<slug>/tasks.md from model.tasks[] — VIEW, not SoT (ADR-39/40)."""
    model = model or load(root)
    tasks = tasks_for_story(model, sid)
    if not tasks:
        raise ValueError(f"no typed tasks for {sid} — run assign-tasks first")
    slug = brief_slug_for_story(root, sid, model)
    out_dir = root / "specs" / slug
    out_path = out_dir / "tasks.md"
    lines = [
        f"# {slug} Tasks",
        "",
        "<!-- O-M3TYPED — rendered from model.tasks[]; do not treat as SoT -->",
        "# ADR-35/40: task IDs + acceptance are harness-derived. Seat fills JUDGMENT only.",
        "",
        "UI surface: waived (API-only).",
        "",
    ]
    for t in sorted(tasks, key=lambda x: int(x.get("seq") or 0)):
        owns = " ".join(t.get("owns") or [])
        findings = t.get("findings") or []
        acc = t.get("acceptance") or []
        goal = (t.get("goal") or "").strip() or (
            "<!-- JUDGMENT: one sentence from brief + SNIPPET — replace -->"
        )
        plan = (t.get("plan") or "").strip()
        role = str(t.get("role") or "").strip().upper()
        lines += [
            f"#### {t.get('id')}: {t.get('title') or t.get('id')}",
            f"**Class**: {t.get('class') or 'rewrite'}",
            f"**Shape**: {t.get('shape') or 'modify'}",
            f"**Port**: {t.get('port')}" if t.get("port") else "**Port**:",
            f"**Role**: {role}" if role else "**Role**:",
            f"**Owns**: `{owns}`" if owns else "**Owns**:",
            f"**Oracle**: {t.get('oracle') or 'absent'}",
            "**Assumes**:",
            f"**Findings**: {', '.join(findings) if findings else '(none)'}",
            f"**Goal**: {goal}",
            "**Target design**:",
        ]
        if owns:
            for o in owns.split():
                lines.append(f"- → `{o}`")
        else:
            lines.append("- <!-- JUDGMENT: legacy → dest mapping -->")
        if plan:
            lines.append(f"**Plan**: {plan}")
        lines.extend(_derived_reimpl_create_lines(t))
        lines.append("**Acceptance**:")
        for a in acc:
            lines.append(f"- {a}")
        if t.get("risk"):
            lines.append(f"**Risk**: {t.get('risk')}")
        lines.append("")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


def render_all_tasks_md(root: Path, model: Optional[dict] = None) -> list[Path]:
    model = model or load(root)
    paths: list[Path] = []
    for st in model.get("stories") or []:
        sid = st.get("id")
        if sid and tasks_for_story(model, sid):
            paths.append(render_tasks_md(root, sid, model))
    return paths


_DAO_FAMILY_RE = re.compile(
    r"(?i)\b(?:DataAccessException|EmptyResultDataAccessException|"
    r"DataRetrievalFailureException|ObjectRetrievalFailureException|"
    r"org\.springframework\.dao)\b"
)

_DAO_EXACT_MAP = (
    "**API mapping**: DataAccessException→PersistenceException; "
    "EmptyResultDataAccessException→NoResultException; "
    "ObjectRetrievalFailureException→EntityNotFoundException "
    "(O-DAOEXMAP / O-M3PRESERVEDAO; omit-throws-only is also OK)."
)


def _derived_reimpl_create_lines(task: dict) -> list[str]:
    """Harness-owned create-procedure + DAO map (W4-566 / O-REIMPLCREATE).

    Port=reimplement Shape=create must declare create-procedure for plan-lint.
    Seat judgment does not invent this form — same family as F-acceptance-derived.
    Also inject the exact DAO map when seat prose mentions Spring DAO types
    (O-M3PRESERVEDAO) without a table — harvest remap goals included.
    """
    port = str(task.get("port") or "").strip().lower()
    shape = str(task.get("shape") or "").strip().lower()
    blob = f"{task.get('goal') or ''} {task.get('plan') or ''}"
    lines: list[str] = []
    if port == "reimplement" and shape == "create":
        owns = " ".join(task.get("owns") or [])
        anchor = owns.split()[0] if owns.split() else "Target .java"
        lines.append(
            "**Procedure**: harvest-from-staging → API mapping table → first-write "
            f"anchor `{anchor}` (O-REIMPLCREATE / O-RESTCREATE) — harness-derived."
        )
        lines.append(_DAO_EXACT_MAP)
    elif _DAO_FAMILY_RE.search(blob) and "DataAccessException→PersistenceException" not in blob:
        # Seat mentioned Spring DAO remap without exact symbols — harness fills.
        lines.append(_DAO_EXACT_MAP)
    return lines


def typed_task_body(task: dict) -> str:
    """Markdown body for one typed task (VIEW shape for plan-lint checks).

    F-lint-reads-store: plan-lint builds bodies from model.tasks[], never by
    parsing specs/**/tasks.md as SoT.
    """
    owns = " ".join(task.get("owns") or [])
    findings = task.get("findings") or []
    acc = task.get("acceptance") or []
    goal = (task.get("goal") or "").strip() or (
        "<!-- JUDGMENT: one sentence from brief + SNIPPET — replace -->"
    )
    plan = (task.get("plan") or "").strip()
    role = str(task.get("role") or "").strip().upper()
    lines = [
        f"**Class**: {task.get('class') or 'rewrite'}",
        f"**Shape**: {task.get('shape') or 'modify'}",
        f"**Port**: {task.get('port')}" if task.get("port") else "**Port**:",
        f"**Role**: {role}" if role else "**Role**:",
        f"**Owns**: `{owns}`" if owns else "**Owns**:",
        f"**Oracle**: {task.get('oracle') or 'absent'}",
        "**Assumes**:",
        f"**Findings**: {', '.join(findings) if findings else '(none)'}",
        f"**Goal**: {goal}",
        "**Target design**:",
    ]
    if owns:
        for o in owns.split():
            lines.append(f"- → `{o}`")
    else:
        lines.append("- <!-- JUDGMENT: legacy → dest mapping -->")
    if plan:
        lines.append(f"**Plan**: {plan}")
    # W4-566: derive create-procedure so seats are not asked to invent form.
    lines.extend(_derived_reimpl_create_lines(task))
    lines.append("**Acceptance**:")
    for a in acc:
        lines.append(f"- {a}")
    if task.get("risk"):
        lines.append(f"**Risk**: {task.get('risk')}")
    lines.append("")
    return "\n".join(lines)


def lint_typed_task_store(model: dict, sid: str) -> list[str]:
    """Structural lint on model.tasks[] (F-lint-reads-store).

    RED names the task id when owns/goal/unit_keys are dishonest.
    """
    reds: list[str] = []
    tasks = tasks_for_story(model, sid)
    if not tasks:
        reds.append(f"LINT:typed-store: no model.tasks[] for {sid}")
        return reds
    seen: set[str] = set()
    for t in tasks:
        tid = str(t.get("id") or "?")
        if tid in seen:
            reds.append(f"LINT:dup-ids: {tid}: task id used more than once")
        seen.add(tid)
        owns = list(t.get("owns") or [])
        keys = list(t.get("unit_keys") or [])
        goal = (t.get("goal") or "").strip()
        if not keys:
            reds.append(f"LINT:typed-keys: {tid}: missing unit_keys")
        if not owns:
            reds.append(f"LINT:typed-owns: {tid}: missing owns")
        if "JUDGMENT" in goal or len(goal) < 20:
            reds.append(
                f"LINT:typed-goal: {tid}: goal unfilled/short "
                f"(len={len(goal)}; seat judgment required)"
            )
        cls = (t.get("class") or "").lower()
        if cls not in ("rewrite", "infer"):
            reds.append(f"LINT:typed-class: {tid}: class must be rewrite|infer")
    # SCC atomicity — typed path already in lint_scc_atomic
    reds.extend(lint_scc_atomic(model, "", sid))
    return reds


def upsert_task_judgment(
    root: Path,
    *,
    unit_keys: list[str],
    goal: str,
    plan: str = "",
    risk: str = "",
    payload: Optional[dict] = None,
) -> dict:
    """Write-inversion upsert — refuses seat-authored id/acceptance (ADR-35 falsifiers)."""
    payload = payload or {}
    if "id" in payload and payload.get("id") not in (None, ""):
        raise ValueError("F-taskid-generated: seat must not author task id")
    if "acceptance" in payload and payload.get("acceptance") not in (None, "", [], {}):
        raise ValueError("F-acceptance-derived: seat must not author acceptance")
    model = load(root)
    keys_sorted = sorted(unit_keys)
    found = None
    for t in model.get("tasks") or []:
        if sorted(t.get("unit_keys") or []) == keys_sorted:
            found = t
            break
    if found is None:
        raise ValueError(f"no typed task for unit_keys={keys_sorted}")
    found["goal"] = (goal or "").strip()
    found["plan"] = (plan or "").strip()
    found["risk"] = (risk or "").strip()
    found["filled"] = bool(found["goal"]) and len(found["goal"]) >= 20
    # Primary = condensation members[0] order stored on the task (W4-553),
    # not sorted(unit_keys)[0] — assign_tasks and upsert must agree.
    stored = list(found.get("unit_keys") or [])
    primary_key = stored[0] if stored else (keys_sorted[0] if keys_sorted else "")
    primary = unit_by_key(model, primary_key) if primary_key else None
    if primary:
        found["acceptance"] = derive_acceptance(primary)
        d = primary.get("decision") if isinstance(primary.get("decision"), dict) else {}
        found["role"] = str((d or {}).get("role") or found.get("role") or "UNDECIDED").upper()
    save(root, model)
    render_tasks_md(root, found["sid"], model)
    return found


def lint_scc_atomic(model: dict, tasks_text: str, sid: str) -> list[str]:
    """M3: each intersecting SCC owned by exactly one task (ADR-24 §2.6).

    ADR-35: when model.tasks[] is bound for sid, prefer typed ownership
    (F-prose-rendered — do not parse tasks.md into state).
    """
    reds: list[str] = []
    story_units = {u["key"] for u in units_for_story(model, sid)}
    if not story_units:
        return reds
    typed = tasks_for_story(model, sid)
    if typed:
        for scc in model.get("sccs") or []:
            members = set(scc.get("members") or [])
            if not members <= story_units:
                if members & story_units:
                    reds.append(
                        f"LINT:scc-atomic: {scc['id']} intersects {sid} but not fully "
                        f"assigned to the story (M2 invariant broken)"
                    )
                continue
            owners = [
                t.get("id")
                for t in typed
                if members <= set(t.get("unit_keys") or [])
                or t.get("scc_id") == scc["id"]
            ]
            if len(owners) != 1:
                reds.append(
                    f"LINT:scc-atomic: {scc['id']} must be owned by exactly one typed task; "
                    f"found {len(owners)} ({', '.join(owners) or 'none'})"
                )
        return reds
    # Legacy prose path (pre-ADR-35 tips)
    heads = list(
        re.finditer(
            r"^(#{2,6})\s+(T[-A-Za-z0-9]*\d+[A-Za-z]*)\s*:\s*(.+)$",
            tasks_text,
            re.M,
        )
    )
    task_bodies: list[tuple[str, str]] = []
    for i, m in enumerate(heads):
        start = m.end()
        end = heads[i + 1].start() if i + 1 < len(heads) else len(tasks_text)
        task_bodies.append((m.group(2), tasks_text[start:end]))

    def task_owns(body: str) -> set[str]:
        paths = set(
            re.findall(
                r"(?im)^\s*\*?\*?(?:Owns|Absorbs|Target(?:\s*design)?)\*?\*?\s*:\s*`?([^`\n]+)`?",
                body,
            )
        )
        # also arrow targets
        paths.update(re.findall(r"src/(?:main|test)/java/[A-Za-z0-9_./]+\.java", body))
        keys: set[str] = set()
        batch = re.search(r"(?i)shape:\s*batch:(SCC-\d+)", body)
        if batch:
            scc = next(
                (s for s in model.get("sccs") or [] if s["id"] == batch.group(1)),
                None,
            )
            if scc:
                keys.update(scc.get("members") or [])
        for u in model.get("units") or []:
            tp = u.get("target_path") or ""
            lp = u.get("legacy_path") or ""
            for raw in paths:
                parts = raw.strip().split()
                if not parts:
                    continue
                p = parts[0].strip("`")
                if not p:
                    continue
                # O-ADR24BASENAME: exact Owns/Target paths only.
                if tp and p == tp:
                    keys.add(u["key"])
                if lp and p == lp:
                    keys.add(u["key"])
        return keys

    for scc in model.get("sccs") or []:
        members = set(scc.get("members") or [])
        if not members <= story_units:
            if members & story_units:
                reds.append(
                    f"LINT:scc-atomic: {scc['id']} intersects {sid} but not fully "
                    f"assigned to the story (M2 invariant broken)"
                )
            continue
        owners = []
        for tid, body in task_bodies:
            owned = task_owns(body)
            if members <= owned or re.search(
                rf"(?i)shape:\s*batch:{re.escape(scc['id'])}", body
            ):
                owners.append(tid)
        if len(owners) != 1:
            reds.append(
                f"LINT:scc-atomic: {scc['id']} must be owned by exactly one task; "
                f"found {len(owners)} ({', '.join(owners) or 'none'})"
            )
    return reds


def path_tracked(root: Path, rel: str) -> bool:
    try:
        subprocess.check_output(
            ["git", "-C", str(root), "cat-file", "-e", f"HEAD:{rel}"],
            stderr=subprocess.DEVNULL,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return (root / rel).is_file()


def story_complete(root: Path, model: dict, sid: str) -> tuple[bool, list[str]]:
    """F5: targets present AND story findings not REMAINING in findings-delta."""
    reasons: list[str] = []
    units = units_for_story(model, sid)
    if not units:
        return False, [f"no units bound for {sid}"]
    for u in units:
        tp = u.get("target_path")
        if not tp:
            continue
        if u.get("kind") == "remove":
            if path_tracked(root, tp):
                reasons.append(f"remove target still present: {tp}")
            continue
        if not path_tracked(root, tp):
            reasons.append(f"missing target: {tp}")
    story_fids: list[str] = []
    for st in model.get("stories") or []:
        if st.get("id") == sid:
            story_fids = list(st.get("findings") or [])
            break
    if not story_fids:
        for u in units:
            story_fids.extend(u.get("findings") or [])
        story_fids = sorted(set(story_fids))
    delta = root / "migration" / "findings-delta.txt"
    if delta.is_file() and story_fids:
        dtxt = delta.read_text(encoding="utf-8", errors="replace")
        for fid in story_fids:
            if re.search(
                rf"(?i)(REMAINING|ABSENT-NOT-LANDED).*{re.escape(fid)}"
                rf"|{re.escape(fid)}.*(REMAINING|ABSENT-NOT-LANDED)",
                dtxt,
            ):
                reasons.append(f"finding undischarged: {fid}")
    elif story_fids and not delta.is_file():
        # Fail-closed when findings exist but delta never produced (S01-shaped lie).
        reasons.append("findings-delta.txt absent while story has findings (F5)")
    return (len(reasons) == 0), reasons


def cover_check(root: Path, model: dict) -> list[str]:
    """F8: model covers staging **main** .java (exact path — O-ADR24BASENAME).

    Policy (Wave5 W5-003/W5-005): test sources are out of F8 scope unless a unit
    explicitly owns a src/test path. cover_check must agree with that intent
    (no silent rc=1 on tests).
    """
    errs: list[str] = []
    staging = root / "migration" / "staging"
    if not staging.is_dir():
        return errs
    covered_rels: set[str] = set()
    for u in model.get("units") or []:
        sp = u.get("staging_path") or ""
        lp = u.get("legacy_path") or ""
        if sp:
            covered_rels.add(sp)
        if lp:
            covered_rels.add(f"migration/staging/{lp}")
    for p in staging.rglob("*.java"):
        rel = str(p.relative_to(root))
        # Default F8 scope = main production sources only.
        if "/src/test/" in rel.replace("\\", "/"):
            continue
        if rel in covered_rels:
            continue
        errs.append(f"uncovered staging java: {rel}")
    return errs


def _task_bodies(tasks_text: str) -> list[tuple[str, str]]:
    heads = list(
        re.finditer(
            r"^(#{2,6})\s+(T[-A-Za-z0-9]*\d+[A-Za-z]*)\s*:\s*(.+)$",
            tasks_text,
            re.M,
        )
    )
    out: list[tuple[str, str]] = []
    for i, m in enumerate(heads):
        start = m.end()
        end = heads[i + 1].start() if i + 1 < len(heads) else len(tasks_text)
        out.append((m.group(2), tasks_text[start:end]))
    return out


def _task_owned_kinds(model: dict, body: str) -> set[str]:
    """Kinds of model units owned by a task (Owns/Target/batch:SCC)."""
    paths = set(
        re.findall(
            r"(?im)^\s*\*?\*?(?:Owns|Absorbs|Target(?:\s*design)?)\*?\*?\s*:\s*`?([^`\n]+)`?",
            body,
        )
    )
    paths.update(re.findall(r"src/(?:main|test)/java/[A-Za-z0-9_./]+\.java", body))
    keys: set[str] = set()
    batch = re.search(r"(?i)shape:\s*batch:(SCC-\d+)", body)
    if batch:
        scc = next(
            (s for s in model.get("sccs") or [] if s["id"] == batch.group(1)),
            None,
        )
        if scc:
            keys.update(scc.get("members") or [])
    for u in model.get("units") or []:
        tp = u.get("target_path") or ""
        lp = u.get("legacy_path") or ""
        for raw in paths:
            parts = raw.strip().split()
            if not parts:
                continue
            p = parts[0].strip("`")
            if not p:
                continue
            # O-ADR24BASENAME: exact Owns/Target paths only (same as task_owns).
            if tp and p == tp:
                keys.add(u["key"])
            if lp and p == lp:
                keys.add(u["key"])
    kinds: set[str] = set()
    by_key = {u["key"]: u for u in model.get("units") or []}
    for k in keys:
        u = by_key.get(k)
        if u:
            kinds.add(u.get("kind") or "java")
    # path-only ownership without unit match: infer from suffix
    for raw in paths:
        parts = raw.strip().split()
        if not parts:
            continue
        p = parts[0].strip("`")
        if p.endswith(".java"):
            kinds.add("java")
        elif p.endswith(".properties") or p.endswith(".yml") or p.endswith(".yaml"):
            kinds.add("resources")
        elif p.endswith("pom.xml") or p == "pom.xml":
            kinds.add("pom")
    return kinds


def lint_finding_kind(model: dict, tasks_text: str, sid: str = "") -> list[str]:
    """F9: a finding on a java unit cannot be discharged by a non-java-only task.

    F-lint-reads-store: when typed tasks exist for sid (or any story), prefer
    model.tasks[] — do not parse tasks.md prose into ownership state.
    """
    reds: list[str] = []
    finding_kind = {
        f.get("id"): f.get("kind") or "java" for f in (model.get("findings") or [])
    }
    # also derive from unit bindings
    unit_kind = {u["key"]: u.get("kind") or "java" for u in model.get("units") or []}
    for f in model.get("findings") or []:
        for uk in f.get("units") or []:
            if unit_kind.get(uk) == "java":
                finding_kind[f["id"]] = "java"

    typed: list[dict] = []
    if sid:
        typed = tasks_for_story(model, sid)
    if not typed:
        # Any typed tasks in the model → store path for all stories present
        typed = list(model.get("tasks") or [])
    if typed:
        by_key = {u["key"]: u for u in model.get("units") or []}
        for t in typed:
            tid = str(t.get("id") or "?")
            fids = [str(x) for x in (t.get("findings") or []) if x]
            if not fids:
                continue
            owned_kinds: set[str] = set()
            for k in t.get("unit_keys") or []:
                u = by_key.get(k)
                if u:
                    owned_kinds.add(u.get("kind") or "java")
            for o in t.get("owns") or []:
                p = str(o)
                if p.endswith(".java"):
                    owned_kinds.add("java")
            for fid in fids:
                if finding_kind.get(fid) != "java":
                    continue
                if "java" not in owned_kinds:
                    reds.append(
                        f"LINT:finding-kind: {tid} lists java finding {fid} but owns "
                        f"no java unit (kinds={sorted(owned_kinds) or ['none']}) (F9)"
                    )
        return reds

    for tid, body in _task_bodies(tasks_text):
        fm = re.search(r"(?im)^\s*\*?\*?Findings\*?\*?\s*:\s*(.+)$", body)
        if not fm:
            continue
        raw = fm.group(1).strip()
        if not raw or raw.startswith("(none") or raw == "-":
            continue
        fids = [
            x.strip().strip("`")
            for x in re.split(r"[,;\s]+", raw)
            if x.strip() and re.match(r"^[a-z]", x.strip())
        ]
        owned_kinds = _task_owned_kinds(model, body)
        for fid in fids:
            if finding_kind.get(fid) != "java":
                continue
            if "java" not in owned_kinds:
                reds.append(
                    f"LINT:finding-kind: {tid} lists java finding {fid} but owns "
                    f"no java unit (kinds={sorted(owned_kinds) or ['none']}) (F9)"
                )
    return reds


def skeleton_condensation_units(model: dict, sid: str) -> list[dict]:
    """Required SCC skeleton preseed — one entry per condensation unit in story order.

    Each entry: {kind: scc|singleton, id, owns: [target_path...], members: [keys]}
    """
    units = {u["key"]: u for u in units_for_story(model, sid)}
    if not units:
        return []
    out: list[dict] = []
    seen: set[str] = set()
    for item in order_for_story(model, sid):
        if item.startswith("SCC-"):
            scc = next((s for s in model.get("sccs") or [] if s["id"] == item), None)
            if not scc:
                continue
            members = [m for m in (scc.get("members") or []) if m in units]
            if not members:
                continue
            owns = [
                units[m]["target_path"]
                for m in members
                if units[m].get("target_path")
            ]
            out.append(
                {
                    "kind": "scc",
                    "id": item,
                    "owns": owns,
                    "members": members,
                    "title": f"{item} convert-together — skeleton (fill from brief)",
                }
            )
            seen.update(members)
        elif item in units:
            u = units[item]
            out.append(
                {
                    "kind": "singleton",
                    "id": item,
                    "owns": [u["target_path"]] if u.get("target_path") else [],
                    "members": [item],
                    "title": f"{(u.get('target_fqn') or item).rsplit('.', 1)[-1]} — skeleton (fill from brief)",
                }
            )
            seen.add(item)
    # leftovers not in order (non-java etc.)
    for k, u in units.items():
        if k in seen:
            continue
        out.append(
            {
                "kind": "singleton",
                "id": k,
                "owns": [u["target_path"]] if u.get("target_path") else [],
                "members": [k],
                "title": f"{Path(u.get('target_path') or k).name} — skeleton (fill from brief)",
            }
        )
    return out


def render_dependency_order_md(model: dict) -> str:
    """One-way human view from the model (condensation order)."""
    units = {u["key"]: u for u in model.get("units") or [] if u.get("kind") == "java"}
    lines = [
        "# Legacy dependency analysis (scripted, M1 — view of model.json)",
        "",
        f"- Classes: {len(units)}; model order entries: {len(model.get('order') or [])}",
        "- Conversion order lists condensation units (SCC id or singleton) — not flattened SCC members.",
        "- Circular groups are SCCs; convert together in ONE task.",
        "",
        "## God nodes (highest fan-in)",
        "",
        "| class | fan-in | fan-out |",
        "|---|---|---|",
    ]
    top = sorted(units.values(), key=lambda u: (-u.get("fan_in", 0), u["key"]))[:5]
    for u in top:
        lines.append(
            f"| {u['key']} | {u.get('fan_in', 0)} | {u.get('fan_out', 0)} |"
        )
    lines += ["", "## Conversion order (dependencies first — condensation units)", ""]
    for i, item in enumerate(model.get("order") or [], 1):
        if item.startswith("SCC-"):
            scc = next((s for s in model.get("sccs") or [] if s["id"] == item), None)
            if scc:
                members = ", ".join(
                    f"{m} ({units[m]['legacy_path']})" if m in units else m
                    for m in scc["members"]
                )
                lines.append(f"{i}. {item} — convert together: {members}")
            else:
                lines.append(f"{i}. {item}")
        else:
            u = units.get(item)
            if u:
                mark = " — god-node: characterization tests first" if u.get("fan_in", 0) >= 3 else ""
                lines.append(f"{i}. {item} ({u['legacy_path']}){mark}")
            else:
                lines.append(f"{i}. {item}")
    for scc in model.get("sccs") or []:
        lines += ["", f"## Circular group {scc['id']} (convert together in ONE task)", ""]
        for m in scc.get("members") or []:
            u = units.get(m)
            lines.append(f"- {m} ({u['legacy_path'] if u else '?'})")
    lines.append("")
    return "\n".join(lines)


def lint_stories_partition(model: dict) -> list[str]:
    """F-partition-total: if stories[] is non-empty, every demand-bearing unit
    is in exactly one story (W5-009 / O-ADR24PART).

    Demand-bearing = kind=java OR unit carries findings. Empty stories[] (M1
    pre-assign) is OK.
    """
    stories = model.get("stories") or []
    if not stories:
        return []
    reds: list[str] = []
    claimed: dict[str, str] = {}
    for s in stories:
        sid = s.get("id") or "?"
        for k in s.get("units") or []:
            if k in claimed:
                reds.append(
                    f"O-ADR24PART RED: unit {k} dual-owned by {claimed[k]} and {sid}"
                )
            else:
                claimed[k] = sid
    unit_by_key = {u["key"]: u for u in model.get("units") or []}
    for k in list(claimed):
        if k not in unit_by_key:
            reds.append(f"O-ADR24PART RED: ghost unit {k} in stories (not in units[])")
    must = {
        u["key"]
        for u in model.get("units") or []
        if u.get("kind") == "java" or (u.get("findings") or [])
    }
    missing = sorted(must - set(claimed))
    if missing:
        reds.append(
            f"O-ADR24PART RED: {len(missing)} demand-bearing unit(s) unassigned: "
            f"{missing[:8]}"
        )
    return reds


def cmd_emit(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    legacy = Path(args.legacy).resolve()
    prev_stories = None
    mp = root / MODEL_REL
    if mp.is_file() and not args.fresh_stories:
        try:
            prev_stories = load(root).get("stories") or []
        except Exception:
            prev_stories = None
    model = build_model(root, legacy, preserve_stories=prev_stories)
    bind_reds = list(model.pop("_bind_reds", []) or [])
    # W5-009: preserved partitions must still satisfy totality after unit-set change
    part_reds = lint_stories_partition(model)
    save(root, model)
    if bind_reds or part_reds:
        for r in bind_reds + part_reds:
            print(r, file=sys.stderr)
        print(
            "O-ADR24 emit RED: bind/partition invariant failed",
            file=sys.stderr,
        )
        return 1
    # one-way markdown view
    dep_md = root / "migration" / "dependency-order.md"
    # Preserve appended codegen/tag demand sections if present after marker
    prior_extra = ""
    if dep_md.is_file():
        old = dep_md.read_text(encoding="utf-8", errors="replace")
        # keep trailing sections that are not part of core render
        for marker in (
            "## Codegen demand",
            "## Tag demand",
            "O-CODEGENDEMAND",
            "O-TAGDEMAND",
        ):
            if marker in old:
                prior_extra = "\n" + old[old.index(marker) :]
                break
    core = render_dependency_order_md(model)
    # If we replaced conversion order with condensation, still allow appendices
    # from subsequent analyze.sh steps — those append after this write.
    dep_md.write_text(core + prior_extra, encoding="utf-8")
    errs = cover_check(root, model)
    if errs:
        print(f"O-ADR24 cover WARN: {len(errs)} staging gaps (F8)", file=sys.stderr)
        for e in errs[:10]:
            print(f"  {e}", file=sys.stderr)
    print(
        f"O-ADR24 emit: units={len(model['units'])} sccs={len(model['sccs'])} "
        f"order={len(model['order'])} → {MODEL_REL}"
    )
    return 0


def cmd_assign(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = assign_stories(root)
    print(
        f"O-ADR24 assign_stories: stories={len(model.get('stories') or [])} OK"
    )
    return 0


def cmd_context(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    if args.scope:
        scope = [p for p in re.split(r"[\s,]+", args.scope) if p]
        print(context_for_scope(model, scope, root=root))
    else:
        print(context_for(model, args.sid, root=root))
    return 0


def cmd_context_profile(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    print(
        context_for_profile(
            load(root),
            root=root,
            undecided_only=bool(getattr(args, "undecided_only", False)),
            limit=int(getattr(args, "limit", 0) or 0),
            legacy=getattr(args, "legacy", None),
        )
    )
    return 0


def cmd_context_m2(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    print(context_for_m2(root))
    return 0


def cmd_assign_tasks(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = assign_tasks(root)
    n = len(model.get("tasks") or [])
    sids = sorted({t.get("sid") for t in (model.get("tasks") or []) if t.get("sid")})
    print(f"O-ADR35 assign-tasks: tasks={n} stories={len(sids)} ({','.join(sids)})")
    return 0


def cmd_render_tasks(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    if not (model.get("tasks") or []):
        model = assign_tasks(root, model)
    sid = (getattr(args, "sid", None) or "").strip()
    if sid:
        p = render_tasks_md(root, sid, model)
        print(f"O-ADR35 render-tasks: {p}")
        return 0
    paths = render_all_tasks_md(root, model)
    for p in paths:
        print(f"O-ADR35 render-tasks: {p}")
    print(f"O-ADR35 render-tasks: done n={len(paths)}")
    return 0


def cmd_emit_profile_skeleton(args: argparse.Namespace) -> int:
    return emit_profile_skeleton(Path(args.root).resolve())


def cmd_lint_scc(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    text = Path(args.tasks).read_text(encoding="utf-8", errors="replace")
    reds = lint_scc_atomic(model, text, args.sid)
    for r in reds:
        print(r)
    return 1 if reds else 0


def cmd_lint_finding_kind(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    text = Path(args.tasks).read_text(encoding="utf-8", errors="replace")
    reds = lint_finding_kind(model, text)
    for r in reds:
        print(r)
    return 1 if reds else 0


def cmd_story_complete(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    ok, reasons = story_complete(root, model, args.sid)
    if ok:
        print(f"story_complete {args.sid}: OK")
        return 0
    print(f"story_complete {args.sid}: RED")
    for r in reasons:
        print(f"  - {r}")
    return 1


def cmd_cover(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    model = load(root)
    errs = cover_check(root, model)
    for e in errs:
        print(e)
    return 1 if errs else 0


def main() -> int:
    ap = argparse.ArgumentParser(description="ADR-24 migration model")
    # Parent so `--root` works before or after the subcommand.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--root", default=".")
    sub = ap.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("emit", parents=[common])
    e.add_argument("--legacy", default="/projects/legacy")
    e.add_argument("--fresh-stories", action="store_true")
    e.set_defaults(func=cmd_emit)

    a = sub.add_parser("assign-stories", parents=[common])
    a.set_defaults(func=cmd_assign)

    c = sub.add_parser("context-for", parents=[common])
    c.add_argument("sid", nargs="?", default="")
    c.add_argument("--scope", default="")
    c.set_defaults(func=cmd_context)

    cp = sub.add_parser("context-for-profile", parents=[common])
    cp.add_argument(
        "--undecided-only",
        action="store_true",
        help="O-PROF1OF79STOP: project only units still needing a credited decision",
    )
    cp.add_argument(
        "--limit",
        type=int,
        default=0,
        help="O-PROF1OF79STOP: cap projected units (decision batch size)",
    )
    cp.add_argument(
        "--legacy",
        default=None,
        help="Legacy root for undecided-only evidence resolve (default: sibling legacy/)",
    )
    cp.set_defaults(func=cmd_context_profile)

    cm2 = sub.add_parser(
        "context-for-m2",
        parents=[common],
        help="ADR-34 projected M2 facts (F-no-discovery)",
    )
    cm2.set_defaults(func=cmd_context_m2)

    at = sub.add_parser(
        "assign-tasks",
        parents=[common],
        help="ADR-35 generate model.tasks[] (harness IDs + derived acceptance)",
    )
    at.set_defaults(func=cmd_assign_tasks)

    rt = sub.add_parser(
        "render-tasks",
        parents=[common],
        help="ADR-35/39 render tasks.md VIEW from model.tasks[]",
    )
    rt.add_argument("--sid", default="", help="one story; default=all")
    rt.set_defaults(func=cmd_render_tasks)

    sk = sub.add_parser("emit-profile-skeleton", parents=[common])
    sk.set_defaults(func=cmd_emit_profile_skeleton)

    l = sub.add_parser("lint-scc-atomic", parents=[common])
    l.add_argument("tasks")
    l.add_argument("sid")
    l.set_defaults(func=cmd_lint_scc)

    fk = sub.add_parser("lint-finding-kind", parents=[common])
    fk.add_argument("tasks")
    fk.set_defaults(func=cmd_lint_finding_kind)

    s = sub.add_parser("story-complete", parents=[common])
    s.add_argument("sid")
    s.set_defaults(func=cmd_story_complete)

    k = sub.add_parser("cover-check", parents=[common])
    k.set_defaults(func=cmd_cover)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
