apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - role.yaml
  - rolebinding.yaml
  - catalog-insights-role.yaml
  - catalog-insights-rolebinding.yaml
  - evalhub-model-auth-provisioner-rbac.yaml
  - evalhub-model-auth-provisioner-job.yaml
