{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_POWER_USAGE)" }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_SM_CLOCK", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}