apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: nemotron-3-nano-30b-a3b
  namespace: maas
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: "NVIDIA Nemotron 3 Nano 30B A3B FP8"
spec:
  modelRef:
    kind: LLMInferenceService
    name: nemotron-3-nano-30b-a3b
