---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agent-profile-claude-sonnet-5-5.yaml
- agent-profile-gpt-4-1.yaml
- agent-profile-gpt-6-luna.yaml
- playground-endpoint-provisioner-rbac.yaml
- playground-endpoint-provisioner-job.yaml
