apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: rhoai-mlflow-artifacts
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
