apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-ai-aa-mcp-servers
  namespace: redhat-ods-applications
data:
  Slack-MCP: |
    {
      "url": "http://slack-mcp.coding-assistant.svc:8080/sse",
      "transport": "sse",
      "description": "Post messages and notifications to Slack channels (Slack MCP Server). Send alerts and updates to team channels."
    }
