apiVersion: v1
kind: Secret
metadata:
  name: rhoai-workbench-connection
  namespace: demo-sandbox
  labels:
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: sandbox-storage
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/component: storage-connections
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    opendatahub.io/connection-type-protocol: s3
    openshift.io/display-name: Workbench
type: Opaque
