apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# OpenShift Dev Spaces with Continue AI code assistant
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_dev_spaces/

resources:
  - devspaces/namespace.yaml
  - devspaces/operatorgroup.yaml
  - devspaces/subscription.yaml
  - devspaces/checluster.yaml
  - devspaces/workspaces.yaml
