apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "12"
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://maas:maas-controller-db-2026@postgres:5432/maas?sslmode=disable"
