apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    openshift.io/description: "Red Hat build of Kueue Operator"
    openshift.io/display-name: "Red Hat build of Kueue Operator"
  labels:
    openshift.io/cluster-monitoring: "true"
