#!/usr/bin/env bash
# RHDH runtime catalog generator (B2). Runs from the rhdh-catalog-bundle
# ConfigMap: this script, render_catalog.py, the catalog and every template
# and skeleton file, generated by kustomize from ONE checkout. Consumed by
# BOTH the Sync-hook Job (immediate regeneration on full syncs) and the
# refresh CronJob (convergence after the selective syncs that skip hooks;
# SKIP_IF_CURRENT=true exits fast when the published catalog already carries
# this bundle at this revision).
#
# The revision is the one Argo CD synced, never the branch head: the bundle
# name carries a content hash, so a catalog-only or template-only commit IS a
# manifest change Argo applies, and the old reason to chase HEAD is gone.
# Nothing is published unless every bundled file is what that revision holds
# (FACTORY_BUNDLE_MISMATCH) and the rendered catalog resolves every
# placeholder; on any refusal the runtime catalog stays as it was.
set -euo pipefail

SRC="${BUNDLE_DIR:-/bundle}"
BUNDLE="$(mktemp -d /tmp/rhdh-catalog-bundle.XXXXXX)"
# one local copy per invocation: a projected-volume update mid-run cannot mix
# two generations of the bundle
for f in "${SRC}"/*; do
  [ -f "$f" ] && cp "$f" "${BUNDLE}/"
done
RENDER="python3 ${BUNDLE}/jobs__catalog__render_catalog.py"
BUNDLE_ID=$(${RENDER} digest --bundle "${BUNDLE}")

APP_SYNC_REVISION=$(oc get application 050-advanced-app-platform -n openshift-gitops \
  -o jsonpath='{.status.operationState.syncResult.revision}' 2>/dev/null || true)
[ -z "$APP_SYNC_REVISION" ] && APP_SYNC_REVISION=$(oc get application 050-advanced-app-platform -n openshift-gitops \
  -o jsonpath='{.status.sync.revision}' 2>/dev/null || true)
APP_REPO_URL=$(oc get application 050-advanced-app-platform -n openshift-gitops \
  -o jsonpath='{.spec.source.repoURL}' 2>/dev/null || true)
[ -z "$APP_REPO_URL" ] && APP_REPO_URL="https://github.com/adnan-drina/rhoai3-coding-demo.git"
REPO_NO_GIT="${APP_REPO_URL%.git}"
if [ -n "${CATALOG_RAW_BASE:-}" ]; then
  # tests only: a file:// repository standing in for raw.githubusercontent.com
  RAW_BASE="${CATALOG_RAW_BASE}"
elif [[ "$REPO_NO_GIT" =~ ^https://github.com/([^/]+)/([^/]+)$ ]]; then
  RAW_BASE="https://raw.githubusercontent.com/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
else
  echo "ERROR: Unsupported repo URL '${APP_REPO_URL}'"
  exit 1
fi

if [ "${SKIP_IF_CURRENT:-false}" = "true" ]; then
  STAMPED=$(oc get configmap catalog-runtime-rhdh -n rhdh \
    -o jsonpath='{.metadata.annotations.rhoai3\.redhat\.com/catalog-revision}' 2>/dev/null || true)
  STAMPED_BUNDLE=$(oc get configmap catalog-runtime-rhdh -n rhdh \
    -o jsonpath='{.metadata.annotations.rhoai3\.redhat\.com/catalog-bundle}' 2>/dev/null || true)
  PENDING=$(oc get configmap catalog-runtime-rhdh -n rhdh \
    -o jsonpath='{.data.all\.yaml}' 2>/dev/null | grep -c -E "pending.local|__RHOAI3_" || true)
  if [ -n "$STAMPED" ] && [ "$STAMPED" = "$APP_SYNC_REVISION" ] && [ "$STAMPED_BUNDLE" = "$BUNDLE_ID" ] && [ "${PENDING:-0}" = "0" ]; then
    echo "Catalog current (bundle ${BUNDLE_ID:0:16} at ${STAMPED}, no pending links); nothing to do"
    exit 0
  fi
  echo "Catalog stale (stamped=${STAMPED:-none}/${STAMPED_BUNDLE:0:16}, synced=${APP_SYNC_REVISION}/${BUNDLE_ID:0:16}, pending-links=${PENDING:-0}); regenerating"
fi

${RENDER} verify --bundle "${BUNDLE}" --raw-base "${RAW_BASE}" --revision "${APP_SYNC_REVISION}"

echo "Discovering Dev Spaces route..."
DEVSPACES_HOST=$(oc get route devspaces -n openshift-devspaces -o jsonpath='{.spec.host}' 2>/dev/null || true)
if [ -z "$DEVSPACES_HOST" ]; then
  DEVSPACES_HOST=$(oc get route -n openshift-devspaces --no-headers 2>/dev/null \
    | awk '/devspaces/ {print $2; exit}' || true)
fi
if [ -z "$DEVSPACES_HOST" ]; then
  # On a first-ever sync the CheCluster (wave 10) has not created the
  # route yet; the host is deterministic, derive it from the ingress domain.
  APPS_DOMAIN=$(oc get ingresses.config.openshift.io cluster \
    -o jsonpath='{.spec.domain}' 2>/dev/null || true)
  if [ -n "$APPS_DOMAIN" ]; then
    DEVSPACES_HOST="devspaces.${APPS_DOMAIN}"
    echo "Dev Spaces route not created yet; derived host ${DEVSPACES_HOST} from cluster ingress domain"
  fi
fi
if [ -z "$DEVSPACES_HOST" ]; then
  echo "ERROR: Dev Spaces route not found and cluster ingress domain unavailable"
  exit 1
fi

# Coolstore dev route (deployed-app link on the inventory component);
# tolerate absence — the wave-21 Route may not exist on first sync.
COOLSTORE_HOST=$(oc get route coolstore-inventory-service -n coolstore-dev \
  -o jsonpath='{.spec.host}' 2>/dev/null || true)
SONARQUBE_HOST=$(oc get route sonarqube -n sonarqube \
  -o jsonpath='{.spec.host}' 2>/dev/null || true)

# In-cluster MaaS route for migration workspaces. The app-migration template
# reads these two values from the platform entity and stamps a pod hostAlias
# at creation, so no workspace starts on the public ELB path. Read from the
# same objects scripts/patch-workspace-maas-route.sh reads; render refuses
# to publish without valid values.
MAAS_HOST=$(oc get gateway maas-default-gateway -n openshift-ingress \
  -o jsonpath='{.spec.listeners[?(@.name=="https")].hostname}' 2>/dev/null || true)
MAAS_INTERNAL_IP=$(oc get service maas-gateway-internal -n openshift-ingress \
  -o jsonpath='{.spec.clusterIP}' 2>/dev/null || true)

echo "Rendering runtime catalog (bundle ${BUNDLE_ID:0:16} at ${APP_SYNC_REVISION})..."
# The Backstage CR consumes this ConfigMap and creates the RHDH Route later;
# TechDocs links stay relative during catalog bootstrap (empty RHDH URL).
${RENDER} render --bundle "${BUNDLE}" --out ${BUNDLE}/.catalog-runtime.yaml \
  --revision "${APP_SYNC_REVISION}" --devspaces-url "https://${DEVSPACES_HOST}" --rhdh-url "" \
  --coolstore-url "https://${COOLSTORE_HOST:-coolstore-pending.local}" \
  --sonarqube-url "https://${SONARQUBE_HOST:-sonarqube-pending.local}" \
  --maas-host "${MAAS_HOST}" --maas-internal-ip "${MAAS_INTERNAL_IP}"

python3 - ${BUNDLE}/.catalog-runtime.yaml ${BUNDLE}/.catalog-patch.json "${APP_SYNC_REVISION}" "${BUNDLE_ID}" <<'PY'
import json
import pathlib
import sys

content = pathlib.Path(sys.argv[1]).read_text()
pathlib.Path(sys.argv[2]).write_text(json.dumps({
    "metadata": {"annotations": {"rhoai3.redhat.com/catalog-revision": sys.argv[3],
                                 "rhoai3.redhat.com/catalog-bundle": sys.argv[4]}},
    "data": {"all.yaml": content}}))
PY

if oc get configmap catalog-runtime-rhdh -n rhdh >/dev/null 2>&1; then
  oc patch configmap catalog-runtime-rhdh -n rhdh --type=merge -p "$(cat ${BUNDLE}/.catalog-patch.json)"
else
  oc create configmap catalog-runtime-rhdh -n rhdh --from-file=all.yaml=${BUNDLE}/.catalog-runtime.yaml
  oc annotate configmap catalog-runtime-rhdh -n rhdh "rhoai3.redhat.com/catalog-revision=${APP_SYNC_REVISION}" \
    "rhoai3.redhat.com/catalog-bundle=${BUNDLE_ID}" --overwrite
fi

echo "Runtime catalog generated from bundle ${BUNDLE_ID:0:16} at revision ${APP_SYNC_REVISION}"

# Template Locations are pinned to the published revision (B2), so each
# re-stamp registers one new Location; the ones for any OTHER revision are
# superseded and pruned here (Lead:catalog-location-must-not-accumulate).
# No catalog API token is provisioned; same postgres path as
# scripts/delete-scaffolded-project.sh. Best-effort: a missing postgres pod
# must not fail catalog generate.
PSQL_POD=$(oc get pods -n rhdh --no-headers 2>/dev/null \
  | awk '/psql|postgres/ {print $1; exit}' || true)
if [ -n "$PSQL_POD" ]; then
  if oc exec -n rhdh "$PSQL_POD" -- psql -d backstage_plugin_catalog -v ON_ERROR_STOP=1 -c "
    DELETE FROM locations
    WHERE target ~ '/blob/[0-9a-f]{40}/gitops/stages/050-advanced-app-platform/base/rhdh/templates/[^/]+/template\\.yaml'
      AND target !~ '/blob/${APP_SYNC_REVISION}/';
    DELETE FROM refresh_state
    WHERE entity_ref LIKE 'location:%'
      AND unprocessed_entity ~ '/blob/[0-9a-f]{40}/gitops/stages/050-advanced-app-platform/base/rhdh/templates/'
      AND unprocessed_entity !~ '/blob/${APP_SYNC_REVISION}/';
  "; then
    echo "Pruned template Locations of superseded revisions"
  else
    echo "WARN: Location prune failed; catalog generate already wrote the ConfigMap"
  fi
else
  echo "No postgres pod in rhdh; skip superseded Location prune"
fi
