apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: maas-controller
    monitoring.opendatahub.io/scrape: 'true'
  name: maas-controller-metrics
  namespace: redhat-ods-applications
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      control-plane: maas-controller
