apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Observability stack for MaaS usage monitoring
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/managing_openshift_ai/managing-observability_managing-rhoai

resources:
  - grafana/namespace.yaml
  - grafana/operatorgroup.yaml
  - grafana/subscription.yaml
  - grafana/instance.yaml
  - grafana/datasource.yaml
  - grafana/maas-dashboard.yaml
  - grafana/servicemonitor.yaml
