apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  name: maas-owner-role
  annotations:
    argocd.argoproj.io/sync-wave: '12'
rules:
- apiGroups:
  - maas.opendatahub.io
  resources:
  - maasmodelrefs
  - externalmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
