apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: all-models-access
  namespace: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-wave: "18"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  modelRefs:
    - name: gpt-oss-20b
      namespace: maas
    - name: nemotron-3-nano-30b-a3b
      namespace: maas
    - name: gpt-5-codex
      namespace: maas
    - name: gpt-5-mini
      namespace: maas
  subjects:
    groups:
      - name: "system:authenticated"
      - name: "system:cluster-admins"
      - name: "tier-free-users"
      - name: "tier-premium-users"
      - name: "tier-enterprise-users"
