apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  name: all-models-subscription
  namespace: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-wave: "18"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  owner:
    groups:
      - name: "system:authenticated"
  modelRefs:
    - name: gpt-oss-20b
      namespace: maas
      tokenRateLimits:
        - limit: 50000
          window: "1h"
    - name: nemotron-3-nano-30b-a3b
      namespace: maas
      tokenRateLimits:
        - limit: 50000
          window: "1h"
    - name: openai-gpt-4o
      namespace: maas
      tokenRateLimits:
        - limit: 50000
          window: "1h"
