---
apiVersion: inference.opendatahub.io/v1alpha1
kind: ExternalModel
metadata:
  name: gpt-4-1
  namespace: external-models
  labels:
    app.kubernetes.io/name: gpt-4-1
    app.kubernetes.io/component: external-model
    app.kubernetes.io/part-of: rhoai3-coding-demo
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '16'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: GPT-4.1
spec:
  modelName: gpt-4-1
  externalProviderRefs:
  - ref:
      name: openai
    weight: 100
    targetModel: gpt-4.1
    apiFormat: openai-chat
    path: "/v1/chat/completions"
