---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- hosting-admin-rolebinding.yaml
- openai-provider.yaml
- gpt-6-luna.yaml
- gpt-6-luna-modelref.yaml
- anthropic-provider.yaml
- claude-sonnet-5-5.yaml
- claude-sonnet-5-5-modelref.yaml
