apiVersion: v1
kind: ServiceAccount
metadata:
  name: enable-model-discovery
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: enable-model-discovery
    app.kubernetes.io/part-of: rhoai-platform
    app.kubernetes.io/component: platform-configuration
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
