apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
  labels:
    app.kubernetes.io/name: openshift-nfd
    app.kubernetes.io/part-of: gpu-infra
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: argocd
