apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-api-hybrid-reader
  annotations:
    argocd.argoproj.io/sync-wave: '12'
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - maas.opendatahub.io
  resources:
  - externalmodels
  - maasauthpolicies
  - maasmodelrefs
  - maassubscriptions
  - tenants
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-api-hybrid-reader
  annotations:
    argocd.argoproj.io/sync-wave: '12'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maas-api-hybrid-reader
subjects:
- kind: ServiceAccount
  name: maas-api
  namespace: redhat-ods-applications
