#!/usr/bin/env python3
"""R-SK.13 — the scaffold must be hermetic against the authoring project.

Operator law: scaffold-repo skills are hermetically separate from
project-level skills. Once this scaffold is deployed into a destination repo
and provisioned into a seat, THERE IS NO LINK BACK to the authoring project
(rhoai3-coding-demo). Any path that reaches outside the scaffold root resolves
to nothing at runtime.

The failure is silent, which is why it needs a gate: a missing tool or skill
usually makes a check SKIP or an instruction read as advice, so the seat looks
healthy while an authority the harness believes it has is simply absent.
Found in the E-20260813T131354Z sweep:
  - AGENTS.md pointed at two `.agents/skills/*` platform skills (one of them
    already deleted) — and AGENTS.md is loaded into EVERY session.
  - validate.sh walked `${ROOT}/../../../harness-refactoring/.wake/tools/`
    guessing at a board-side reviewer tool.
  - a schema doc shipped that same escape as its documented default command.

Rules:
  H1  no `.agents/` reference anywhere in the scaffold (platform skill tree)
  H2  no absolute host path (`/Users/`, `/home/<user>/`)
  H3  no authoring-project path (`harness-refactoring/`, `rhoai3-coding-demo`)
      inside executable or config files (`.py`, `.sh`, `.yaml`, `.yml`).
      Markdown PROSE may name them — contracts legitimately say
      "never steal from the authoring trees", and citations may reference a
      board record as long as they do not read as a resolvable path.
  H4  no development-environment token (`.wake/`, `AGENT_LOOP_WAKE`,
      `*-relay.sh`, `*-watch.sh`, `REFACTORING_V1`) in executable/config
      files. Same markdown exemption as H3: contracts may forbid those
      names in prose. Product output a seat worker reads must not point
      at Mac/Cursor tooling (Operator IND / Deputy E-20260814T190102Z).
  H5  scaffold root must not contain `tmp/` (EX-2/EX-3 attic) or
      `REFACTORING_V1.md` (authoring ledger). LG4 / LG3.

Justified exceptions: one path per line in
  .hermes/skills/harness/validate-contracts/references/r-sk13-hermeticity-keep.txt

Usage:
  python3 check-scaffold-hermeticity.py --root .
  python3 check-scaffold-hermeticity.py --root /projects/modernized

Exit codes:
  0  hermetic — no escape found
  1  BLOCK — one or more escapes (printed as PATH:LINE:RULE:detail)
  2  usage / bad root
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

EXEC_SUFFIXES = {".py", ".sh", ".yaml", ".yml"}
TEXT_SUFFIXES = EXEC_SUFFIXES | {".md", ".txt", ".json"}
# `out` = gate verdict outputs, generated by running the gates. They embed
# the absolute run path by design and are NOT scaffold source. (The deeper
# issue — gates writing run-state into the golden tree instead of a temp dir
# — is filed separately; skipping them here keeps this lint honest about
# SOURCE hermeticity rather than flagging its own suite's exhaust.)
SKIP_DIRS = {".git", "__pycache__", "node_modules", "target", ".specify", "out", "tmp"}

RULES = [
    ("H1", re.compile(r"\.agents/"), EXEC_SUFFIXES | {".md", ".txt"}),
    # Absolute path starts only: line-start / whitespace / quote / `=`.
    # Do NOT use `(?<![\w.])` — `>` / `)` before `/home/` (e.g. argparse help
    # `<skills-parent>/home/skill-bundles`) is a relative path fragment, not a
    # host leak (Deputy E-20260813T140743Z H2 false positive).
    # `/home/user/` and `/home/tooling` remain portable Dev Spaces paths.
    ("H2", re.compile(
        r"(?:^|[\s\"'=])/Users/"
        r"|(?:^|[\s\"'=])/home/(?!(?:user|tooling)(?:[/\s\"']|$))[a-z]",
        re.M,
    ), TEXT_SUFFIXES),
    # Trailing slash required so branding comments (`# rhoai3-coding-demo:`)
    # do not false-positive. Negative lookbehind skips the quay.io registry
    # org path used by stamped destination repos (seat k8s/app.yaml).
    ("H3", re.compile(
        r"harness-refactoring/"
        r"|(?<!quay\.io/)rhoai3-coding-demo/"
    ), EXEC_SUFFIXES),
    # Dev-environment class (IND-2). Trailing slash / explicit suffixes so
    # branding comments do not false-positive. Markdown is exempt (H3).
    ("H4", re.compile(
        r"\.wake/"
        r"|AGENT_LOOP_WAKE"
        r"|-relay\.sh"
        r"|-watch\.sh"
        r"|REFACTORING_V1"
    ), EXEC_SUFFIXES),
]

DETAIL = {
    "H1": "references the authoring repo's .agents/ skill tree — absent once deployed",
    "H2": "absolute host path — not portable to a seat",
    "H3": "authoring-project path in an executable/config file — absent once deployed",
    "H4": "development-environment token in an executable/config file — Mac/Cursor tooling, absent once deployed",
    "H5": "scaffold-root leak — EX-2/EX-3 attic or authoring ledger must not ship",
}


def load_keep(root: Path) -> set[str]:
    keep: set[str] = set()
    cand = (
        root
        / ".hermes/skills/harness/validate-contracts/references"
        / "r-sk13-hermeticity-keep.txt"
    )
    if cand.is_file():
        for line in cand.read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                keep.add(line)
    return keep


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--root", default=".", help="scaffold root (default: .)")
    args = ap.parse_args()
    root = Path(args.root)
    if not root.is_dir():
        print(
            f"Error: --root must be an existing directory. Received: {args.root!r}",
            file=sys.stderr,
        )
        return 2

    keep = load_keep(root)
    errs: list[str] = []
    # LG4 / LG3: these two root entries are the known-bad non-product files.
    # Existence is the gate; scanning inside tmp/ is not enough (SKIP_DIRS).
    if (root / "tmp").exists():
        errs.append(
            "tmp:H5:EX-2/EX-3 attic must not ship inside the scaffold (LG4)"
        )
    if (root / "REFACTORING_V1.md").exists():
        errs.append(
            "REFACTORING_V1.md:H5:authoring ledger must not ship (LG3)"
        )
    scanned = 0
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.suffix not in TEXT_SUFFIXES:
            continue
        if set(p.parts) & SKIP_DIRS:
            continue
        rel = p.relative_to(root).as_posix()
        if rel in keep:
            continue
        scanned += 1
        try:
            lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        for n, line in enumerate(lines, 1):
            for rule, rx, suffixes in RULES:
                if p.suffix not in suffixes:
                    continue
                if rx.search(line):
                    errs.append(f"{rel}:{n}:{rule}:{DETAIL[rule]}")

    for e in errs:
        print(e, file=sys.stderr)
    print(f"HERMETICITY_FILES={scanned} VIOLATIONS={len(errs)}")
    return 1 if errs else 0


if __name__ == "__main__":
    raise SystemExit(main())
