apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mcp-servers-configmap.yaml
  - openshift-mcp/serviceaccount.yaml
  - openshift-mcp/deployment.yaml
  - slack-mcp/deployment.yaml
  - brightdata-mcp/deployment.yaml
