#!/usr/bin/env bash
# Restore the decided datasource's isolated instance to the initial state the
# scenario corpus names: drop and recreate the schema, apply the schema asset
# decisions.yaml points at, load the DERIVED baseline data, align every
# generated-identity sequence, and then VERIFY that the baseline the asset
# declares is the baseline the database now holds.
#
# The reset is part of the evidence, not a convenience. A scenario that
# declares reset_before is only meaningful if the state it starts from is the
# state the corpus says it is, and an effect probe on a mutated database
# proves nothing. Credentials come from the environment by the names the
# decision records; nothing here reads or prints a secret.
#
# What it loads changed with ADR-009's baseline-state correction. The engine is
# a decision; the DATA is not. Loading the source's own per-engine seed made
# the destination start from a dataset the corpus never declared -- measured on
# the specimen: 17 different date literals, and a schema that restarts seven
# identity sequences at a fixed 100 where the engine the source was captured on
# continued from the seeded maximum. So the reset loads
# src/main/resources/db/<engine>/baseline-data.sql, which bootstrap-destination
# DERIVES from the declared dataset, and then asserts the row counts and the
# sequence positions inside the database. A tree with no derived asset (an
# older bootstrap) keeps the previous behaviour and says the baseline is
# unverified, which is a fact about the run and belongs in its log.
#
# It talks JDBC through the destination's own driver rather than a command-line
# client: the workspace that runs the comparison has a JDK and that driver on
# disk, and no psql. A reset that cannot run would turn every reset_before
# scenario INCONCLUSIVE, which is a tooling gap masquerading as a finding. The
# verification is therefore SQL the database itself raises on, generated by
# .hermes/skills/migration/bootstrap-destination/scripts/_baseline_data.py --
# the same module that wrote the asset, and the same judgement its
# verify_observations() makes over query results in the selftest.
#
#   reset-parity-db.sh --root /projects/modernized [--driver /path/to/driver.jar]
#   reset-parity-db.sh --root /projects/modernized --print-plan
#
# Exit 0 reset (and verified, when there is a derived baseline), 1 refused, 2 usage.
set -euo pipefail
ROOT=""
DRIVER=""
PRINT_PLAN="no"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; shift 2 ;;
    --driver) DRIVER="${2:-}"; shift 2 ;;
    --print-plan) PRINT_PLAN="yes"; shift ;;
    *) echo "usage: reset-parity-db.sh --root <dest> [--driver <jar>] [--print-plan]" >&2; exit 2 ;;
  esac
done
[[ -n "${ROOT}" && -d "${ROOT}" ]] || { echo "FAIL: --root must be an existing directory" >&2; exit 2; }
ROOT="$(cd "${ROOT}" && pwd)"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASELINE_TOOL="${HERE}/../../../migration/bootstrap-destination/scripts/_baseline_data.py"

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

read -r DB_KIND URL_ENV USER_ENV PASS_ENV SCHEMA_SQL SEED_SQL < <(python3 - "${ROOT}" <<'PYEOF'
import sys
from pathlib import Path
root = Path(sys.argv[1])
sys.path.insert(0, str(root / ".hermes" / "lib"))
from planner.decisions import datasource, load_decisions
ds = datasource(load_decisions(root))
if not ds:
    raise SystemExit("FAIL: RESET the effective datasource is not decided in decisions.yaml")
print(" ".join(str(ds.get(k) or "-") for k in ("db_kind", "jdbc_url_env", "username_env", "password_env", "schema_sql", "seed_sql")))
PYEOF
)

# The derived baseline, when this tree has one: what to load after the schema,
# and what must then be true. Exit 3 says the tree predates it.
BASELINE_FACTS=""
BASELINE_REL=""
BASELINE_RC=0
if [[ -f "${BASELINE_TOOL}" ]]; then
  BASELINE_FACTS="$(python3 "${BASELINE_TOOL}" --root "${ROOT}" --emit-verify "${WORK}/baseline-verify.sql" 2>"${WORK}/baseline.err")" || BASELINE_RC=$?
else
  BASELINE_RC=3
  echo "no baseline translator beside this script (${BASELINE_TOOL})" >"${WORK}/baseline.err"
fi
if [[ "${BASELINE_RC}" == "0" ]]; then
  BASELINE_REL="$(printf '%s\n' "${BASELINE_FACTS}" | sed -n 's/^baseline: //p' | head -1)"
elif [[ "${BASELINE_RC}" == "3" ]]; then
  echo "NOTE: RESET no derived baseline asset in this tree ($(tr -d '\n' <"${WORK}/baseline.err")); loading ${SEED_SQL} and NOT verifying the baseline"
else
  echo "FAIL: RESET the derived baseline asset is unusable: $(tr -d '\n' <"${WORK}/baseline.err")" >&2
  exit 1
fi

SQL_RELS=()
if [[ "${SCHEMA_SQL}" != "-" ]]; then
  SQL_RELS+=("${SCHEMA_SQL}")
fi
if [[ -n "${BASELINE_REL}" ]]; then
  SQL_RELS+=("${BASELINE_REL}")
elif [[ "${SEED_SQL}" != "-" ]]; then
  SQL_RELS+=("${SEED_SQL}")
fi
SQL_FILES=()
for rel in ${SQL_RELS[@]+"${SQL_RELS[@]}"}; do
  [[ -f "${ROOT}/${rel}" ]] || { echo "FAIL: RESET decisions.yaml names ${rel}, which is not in the tree" >&2; exit 1; }
  SQL_FILES+=("${ROOT}/${rel}")
done
if [[ -n "${BASELINE_REL}" ]]; then
  SQL_FILES+=("${WORK}/baseline-verify.sql")
fi

if [[ "${PRINT_PLAN}" == "yes" ]]; then
  echo "plan: reset ${DB_KIND} from ${URL_ENV} (credentials ${USER_ENV}/${PASS_ENV})"
  for rel in ${SQL_RELS[@]+"${SQL_RELS[@]}"}; do echo "apply: ${rel}"; done
  if [[ -n "${BASELINE_REL}" ]]; then
    printf '%s\n' "${BASELINE_FACTS}" | sed -n '2,$p'
    echo "verify: row counts per table and each aligned sequence's next value = max + 1"
  else
    echo "verify: none (no derived baseline asset; the baseline is unverified)"
  fi
  exit 0
fi

URL="${!URL_ENV:-}"
DB_USER="${!USER_ENV:-}"
DB_PASSWORD="${!PASS_ENV:-}"
[[ -n "${URL}" && -n "${DB_USER}" && -n "${DB_PASSWORD}" ]] || { echo "FAIL: RESET ${URL_ENV}, ${USER_ENV} and ${PASS_ENV} must be set (the decision references them by name)" >&2; exit 1; }

# The driver, found under its OWN group directory. A bare artifact glob is not
# a driver: ~/.m2 also holds org.testcontainers:postgresql, which matched
# postgresql-*.jar and produced "No suitable driver found".
if [[ -z "${DRIVER}" ]]; then
  case "${DB_KIND}" in
    postgresql) GROUP_DIR="org/postgresql/postgresql" ;;
    mysql) GROUP_DIR="com/mysql/mysql-connector-j" ;;
    mariadb) GROUP_DIR="org/mariadb/jdbc/mariadb-java-client" ;;
    mssql) GROUP_DIR="com/microsoft/sqlserver/mssql-jdbc" ;;
    h2) GROUP_DIR="com/h2database/h2" ;;
    *) echo "FAIL: RESET no driver coordinate for db_kind ${DB_KIND}; pass --driver" >&2; exit 1 ;;
  esac
  DRIVER="$(find "${HOME}/.m2/repository/${GROUP_DIR}" -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" 2>/dev/null | sort -V | tail -1)"
fi
[[ -n "${DRIVER}" && -f "${DRIVER}" ]] || { echo "FAIL: RESET no ${DB_KIND} JDBC driver found under ~/.m2; pass --driver <jar>" >&2; exit 1; }

javac -d "${WORK}" "${HERE}/reset-db/ResetDb.java" >"${WORK}/javac.log" 2>&1 || { echo "FAIL: RESET could not compile the reset runner: $(tail -3 "${WORK}/javac.log")" >&2; exit 1; }
# read the jar directly: `unzip -l | grep -q` closes the pipe on the first
# match, and under pipefail that reads as a failure (the same trap the stage
# validator hit)
REGISTERS="$(python3 -c 'import sys, zipfile; print("yes" if "META-INF/services/java.sql.Driver" in zipfile.ZipFile(sys.argv[1]).namelist() else "no")' "${DRIVER}" 2>/dev/null || echo no)"
if [[ "${REGISTERS}" != "yes" ]]; then
  echo "FAIL: RESET $(basename "${DRIVER}") registers no JDBC driver; pass --driver <jar>" >&2
  exit 1
fi
# A verification statement that does not hold RAISEs, the runner propagates the
# SQLException, and this script exits non-zero: an unverified baseline is never
# reported as a reset.
java -cp "${DRIVER}:${WORK}" ResetDb "${URL}" "${DB_USER}" "${DB_PASSWORD}" ${SQL_FILES[@]+"${SQL_FILES[@]}"}
if [[ -n "${BASELINE_REL}" ]]; then
  printf '%s\n' "${BASELINE_FACTS}" | sed -n '2,$p'
  echo "OK: reset to the DECLARED initial state and verified (${SQL_RELS[*]}) using $(basename "${DRIVER}")"
else
  echo "OK: reset to the initial state (${SQL_RELS[*]}) using $(basename "${DRIVER}"); baseline UNVERIFIED (no derived asset)"
fi
