apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    machine.openshift.io/GPU: '1'
    machine.openshift.io/memoryMb: '65536'
    machine.openshift.io/vCPU: '8'
    demo.rhoai.io/source-machineset: ocp-wzxl7-worker-us-east-2a-compute
  labels:
    app.kubernetes.io/part-of: gpu-infra
    app.kubernetes.io/name: aws-gpu-machineset
    app.kubernetes.io/component: gpu-worker
    app.kubernetes.io/managed-by: argocd
    cluster-api/accelerator: nvidia-gpu
    machine.openshift.io/cluster-api-cluster: ocp-wzxl7
  name: ocp-wzxl7-gpu-us-east-2a
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-wzxl7
      machine.openshift.io/cluster-api-machineset: ocp-wzxl7-gpu-us-east-2a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-wzxl7
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp-wzxl7-gpu-us-east-2a
        cluster-api/accelerator: nvidia-gpu
        node-role.kubernetes.io/gpu: ''
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          cluster-api/accelerator: nvidia-gpu
          node-role.kubernetes.io/gpu: ''
      providerSpec:
        value:
          ami:
            id: ami-03b58703d4e9ea61a
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ''
              volumeSize: 200
              volumeType: gp3
          capacityReservationId: ''
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp-wzxl7-worker-profile
          instanceType: g6e.2xlarge
          kind: AWSMachineProviderConfig
          metadata: {}
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp-wzxl7-node
          - filters:
            - name: tag:Name
              values:
              - ocp-wzxl7-lb
          subnet:
            filters:
            - name: tag:Name
              values:
              - ocp-wzxl7-subnet-private-us-east-2a
          tags:
          - name: kubernetes.io/cluster/ocp-wzxl7
            value: owned
          - name: Stack
            value: project openshift-cluster-h275t
          - name: config
            value: openshift-cluster
          - name: guid
            value: h275t
          - name: owner
            value: unknown
          - name: uuid
            value: c9cb960c-03b8-54a1-a793-d504657163e3
          userDataSecret:
            name: worker-user-data
      taints:
      - effect: NoSchedule
        key: nvidia-gpu-only
