apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgresql
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: rhoai-platform
    app.kubernetes.io/name: mlflow-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    # Retain experiment metadata if the application is removed from Git.
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 10Gi
