apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-service-ca
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: rhoai-platform
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: configuration
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: "12"
    service.beta.openshift.io/inject-cabundle: "true"
