apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mcp-gateway
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  name: mcp-gateway
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: preview
  installPlanApproval: Automatic
  config:
    resources:
      requests: {cpu: 100m, memory: 128Mi}
      limits: {cpu: 500m, memory: 512Mi}
