# Required for MaaS Gateway API routing
# Ref: https://docs.redhat.com/en/learn/ai-quickstarts/rh-maas-code-assistant
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openshift-default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  controllerName: "openshift.io/gateway-controller/v1"
