apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
  labels:
    app.kubernetes.io/name: nvidia-gpu-operator
    app.kubernetes.io/part-of: gpu-infra
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: argocd
