apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - enablement
  - mlflow
  - evalhub
  - tenant
  - prompts
  - swebench
labels:
  - pairs:
      app.kubernetes.io/part-of: rhoai-platform
      app.kubernetes.io/managed-by: argocd
      demo.rhoai.io/stage: "050"
    includeSelectors: false
