apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: mta
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  href: https://mta.placeholder.example.com
  location: ApplicationMenu
  text: Migration Toolkit for Applications
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://mta.placeholder.example.com/favicon.ico
