apiVersion: v1
kind: Namespace
metadata:
  name: coolstore-dev
  labels:
    app.kubernetes.io/part-of: coolstore
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    openshift.io/description: Deployed Coolstore dev environment for the AI development demo stages
