apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-admin-registry-admin
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "15"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ai-admin
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: rhoai-admins
